// Logging Constants
export const OVERTIME_LOGGING_CONSTANTS = {
  // API Error Logs
  API_ERRORS: {
    FETCH_POLICIES_FAILED: 'FETCH_POLICIES_FAILED',
    FETCH_POLICY_BY_ID_FAILED: 'FETCH_POLICY_BY_ID_FAILED',
    FETCH_NEXT_PAGE_FAILED: 'FETCH_NEXT_PAGE_FAILED',
    FETCH_PREVIOUS_PAGE_FAILED: 'FETCH_PREVIOUS_PAGE_FAILED',
    FETCH_SPECIFIC_PAGE_FAILED: 'FETCH_SPECIFIC_PAGE_FAILED',
    CREATE_POLICY_FAILED: 'CREATE_POLICY_FAILED',
    CREATE_POLICY_DEGRADED: 'CREATE_POLICY_DEGRADED',
    UPDATE_POLICY_FAILED: 'UPDATE_POLICY_FAILED',
    UPDATE_POLICY_DEGRADED: 'UPDATE_POLICY_DEGRADED',
    DELETE_POLICY_FAILED: 'DELETE_POLICY_FAILED',
    DELETE_POLICY_DEGRADED: 'DELETE_POLICY_DEGRADED',
    MANAGE_ASSIGNMENTS_FAILED: 'MANAGE_ASSIGNMENTS_FAILED',
    FETCH_WORKER_COUNT_FAILED: 'FETCH_WORKER_COUNT_FAILED',
    APOLLO_CLIENT_NOT_INITIALIZED: 'APOLLO_CLIENT_NOT_INITIALIZED',
    WIZARD_EDIT_MODE_MISSING_POLICY_ID: 'WIZARD_EDIT_MODE_MISSING_POLICY_ID',
  },

  // Navigation Logs
  NAVIGATION: {
    FEATURE_MOUNTED: 'FEATURE_MOUNTED',
    SETTINGS_HANDLE_MOUNTED: 'SETTINGS_HANDLE_MOUNTED',
    LANDING_PAGE_MOUNTED: 'LANDING_PAGE_MOUNTED',
    FILLED_STATE_MOUNTED: 'FILLED_STATE_MOUNTED',
    DELETE_MODAL_OPENED: 'DELETE_MODAL_OPENED',
  },

  // User Interaction Logs
  USER_INTERACTIONS: {
    SETTINGS_HANDLE_EDIT_CLICKED: 'SETTINGS_HANDLE_EDIT_CLICKED',
    CREATE_POLICY_CLICKED: 'CREATE_POLICY_CLICKED',
    EDIT_POLICY_CLICKED: 'EDIT_POLICY_CLICKED',
    DELETE_MENU_ITEM_CLICKED: 'DELETE_MENU_ITEM_CLICKED',
    DELETE_MODAL_CONFIRMED: 'DELETE_MODAL_CONFIRMED',
    DELETE_MODAL_CANCELLED: 'DELETE_MODAL_CANCELLED',
    ASSIGN_WORKERS_CLICKED: 'ASSIGN_WORKERS_CLICKED',
    LEARN_MORE_CLICKED: 'LEARN_MORE_CLICKED',
    CHECK_LAWS_CLICKED: 'CHECK_LAWS_CLICKED',
    MENU_OPENED: 'MENU_OPENED',
  },

  // Form State Logs
  FORM_STATE: {
    WIZARD_SUBMIT_CREATE_STARTED: 'WIZARD_SUBMIT_CREATE_STARTED',
    WIZARD_SUBMIT_UPDATE_STARTED: 'WIZARD_SUBMIT_UPDATE_STARTED',
    WIZARD_UPDATE_FROM_REVIEW_STARTED: 'WIZARD_UPDATE_FROM_REVIEW_STARTED',
    WIZARD_ASSIGNMENTS_STARTED: 'WIZARD_ASSIGNMENTS_STARTED',
    WIZARD_ASSIGNMENTS_SAVE_STARTED: 'WIZARD_ASSIGNMENTS_SAVE_STARTED',
    WIZARD_VALIDATION_FAILED: 'WIZARD_VALIDATION_FAILED',
  },

  // Success Logs
  SUCCESS: {
    FETCH_POLICIES_SUCCESS: 'FETCH_POLICIES_SUCCESS',
    FETCH_POLICY_BY_ID_SUCCESS: 'FETCH_POLICY_BY_ID_SUCCESS',
    FETCH_NEXT_PAGE_SUCCESS: 'FETCH_NEXT_PAGE_SUCCESS',
    FETCH_PREVIOUS_PAGE_SUCCESS: 'FETCH_PREVIOUS_PAGE_SUCCESS',
    FETCH_SPECIFIC_PAGE_SUCCESS: 'FETCH_SPECIFIC_PAGE_SUCCESS',
    CREATE_POLICY_SUCCESS: 'CREATE_POLICY_SUCCESS',
    UPDATE_POLICY_SUCCESS: 'UPDATE_POLICY_SUCCESS',
    DELETE_POLICY_SUCCESS: 'DELETE_POLICY_SUCCESS',
    MANAGE_ASSIGNMENTS_SUCCESS: 'MANAGE_ASSIGNMENTS_SUCCESS',
  },

  // Wizard Funnel Logs
  WIZARD_FUNNEL: {
    STEP_1_ENTERED: 'WIZARD_STEP_1_ENTERED',
    STEP_2_ENTERED: 'WIZARD_STEP_2_ENTERED',
    STEP_3_ENTERED: 'WIZARD_STEP_3_ENTERED',
    STEP_4_ENTERED: 'WIZARD_STEP_4_ENTERED',
    STEP_1_COMPLETED: 'WIZARD_STEP_1_COMPLETED',
    STEP_2_COMPLETED: 'WIZARD_STEP_2_COMPLETED',
    STEP_3_COMPLETED: 'WIZARD_STEP_3_COMPLETED',
    WIZARD_COMPLETED: 'WIZARD_COMPLETED',
    WIZARD_ABANDONED: 'WIZARD_ABANDONED',
  },

  // Rule Type Selection Logs
  RULE_TYPE: {
    BASIC_SELECTED: 'RULE_TYPE_BASIC_SELECTED',
    CALIFORNIA_SELECTED: 'RULE_TYPE_CALIFORNIA_SELECTED',
    CUSTOM_SELECTED: 'RULE_TYPE_CUSTOM_SELECTED',
  },
} as const;

export const OVERTIME_LOGGING = {
  FEATURE_MOUNTED: OVERTIME_LOGGING_CONSTANTS.NAVIGATION.FEATURE_MOUNTED,
  UNKNOWN_FUNCTIONALITY: 'Component=Overtime Error=UnknownFunctionality',

  SETTINGS_HANDLE_MOUNTED:
    OVERTIME_LOGGING_CONSTANTS.NAVIGATION.SETTINGS_HANDLE_MOUNTED,
  SETTINGS_HANDLE_EDIT_CLICKED:
    OVERTIME_LOGGING_CONSTANTS.USER_INTERACTIONS.SETTINGS_HANDLE_EDIT_CLICKED,
  SETTINGS_HANDLE_GUIDANCE_CLICKED:
    OVERTIME_LOGGING_CONSTANTS.USER_INTERACTIONS.LEARN_MORE_CLICKED,

  LANDING_PAGE_MOUNTED:
    OVERTIME_LOGGING_CONSTANTS.NAVIGATION.LANDING_PAGE_MOUNTED,
  LANDING_PAGE_CREATE_POLICY_CLICKED:
    OVERTIME_LOGGING_CONSTANTS.USER_INTERACTIONS.CREATE_POLICY_CLICKED,
  LANDING_PAGE_EDIT_POLICY_CLICKED:
    OVERTIME_LOGGING_CONSTANTS.USER_INTERACTIONS.EDIT_POLICY_CLICKED,
  LANDING_PAGE_LEARN_MORE_CLICKED:
    OVERTIME_LOGGING_CONSTANTS.USER_INTERACTIONS.LEARN_MORE_CLICKED,
  LANDING_PAGE_CHECK_LAWS_CLICKED:
    OVERTIME_LOGGING_CONSTANTS.USER_INTERACTIONS.CHECK_LAWS_CLICKED,

  FILLED_STATE_MOUNTED:
    OVERTIME_LOGGING_CONSTANTS.NAVIGATION.FILLED_STATE_MOUNTED,
  FILLED_STATE_CREATE_POLICY_CLICKED:
    OVERTIME_LOGGING_CONSTANTS.USER_INTERACTIONS.CREATE_POLICY_CLICKED,
  FILLED_STATE_EDIT_POLICY_CLICKED:
    OVERTIME_LOGGING_CONSTANTS.USER_INTERACTIONS.EDIT_POLICY_CLICKED,
  FILLED_STATE_MENU_OPENED:
    OVERTIME_LOGGING_CONSTANTS.USER_INTERACTIONS.MENU_OPENED,

  DELETE_MENU_ITEM_CLICKED:
    OVERTIME_LOGGING_CONSTANTS.USER_INTERACTIONS.DELETE_MENU_ITEM_CLICKED,
  DELETE_MODAL_OPENED:
    OVERTIME_LOGGING_CONSTANTS.NAVIGATION.DELETE_MODAL_OPENED,
  DELETE_MODAL_CONFIRMED:
    OVERTIME_LOGGING_CONSTANTS.USER_INTERACTIONS.DELETE_MODAL_CONFIRMED,
  DELETE_MODAL_CANCELLED:
    OVERTIME_LOGGING_CONSTANTS.USER_INTERACTIONS.DELETE_MODAL_CANCELLED,

  WIZARD_SUBMIT_CREATE_STARTED:
    OVERTIME_LOGGING_CONSTANTS.FORM_STATE.WIZARD_SUBMIT_CREATE_STARTED,
  WIZARD_SUBMIT_UPDATE_STARTED:
    OVERTIME_LOGGING_CONSTANTS.FORM_STATE.WIZARD_SUBMIT_UPDATE_STARTED,
  WIZARD_UPDATE_FROM_REVIEW_STARTED:
    OVERTIME_LOGGING_CONSTANTS.FORM_STATE.WIZARD_UPDATE_FROM_REVIEW_STARTED,
  WIZARD_ASSIGNMENTS_STARTED:
    OVERTIME_LOGGING_CONSTANTS.FORM_STATE.WIZARD_ASSIGNMENTS_STARTED,
  WIZARD_ASSIGNMENTS_SAVE_STARTED:
    OVERTIME_LOGGING_CONSTANTS.FORM_STATE.WIZARD_ASSIGNMENTS_SAVE_STARTED,
  WIZARD_VALIDATION_FAILED:
    OVERTIME_LOGGING_CONSTANTS.FORM_STATE.WIZARD_VALIDATION_FAILED,

  API_FETCH_POLICIES_FAILED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.FETCH_POLICIES_FAILED,

  API_CREATE_POLICY_SUCCESS:
    OVERTIME_LOGGING_CONSTANTS.SUCCESS.CREATE_POLICY_SUCCESS,
  API_UPDATE_POLICY_SUCCESS:
    OVERTIME_LOGGING_CONSTANTS.SUCCESS.UPDATE_POLICY_SUCCESS,
  API_DELETE_POLICY_SUCCESS:
    OVERTIME_LOGGING_CONSTANTS.SUCCESS.DELETE_POLICY_SUCCESS,
  API_MANAGE_ASSIGNMENTS_SUCCESS:
    OVERTIME_LOGGING_CONSTANTS.SUCCESS.MANAGE_ASSIGNMENTS_SUCCESS,

  API_CREATE_POLICY_FAILED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.CREATE_POLICY_FAILED,
  API_CREATE_POLICY_DEGRADED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.CREATE_POLICY_DEGRADED,
  API_UPDATE_POLICY_FAILED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.UPDATE_POLICY_FAILED,
  API_UPDATE_POLICY_DEGRADED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.UPDATE_POLICY_DEGRADED,
  API_DELETE_POLICY_FAILED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.DELETE_POLICY_FAILED,
  API_DELETE_POLICY_DEGRADED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.DELETE_POLICY_DEGRADED,
  API_MANAGE_ASSIGNMENTS_FAILED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.MANAGE_ASSIGNMENTS_FAILED,

  FETCH_POLICIES_SUCCESS:
    OVERTIME_LOGGING_CONSTANTS.SUCCESS.FETCH_POLICIES_SUCCESS,
  FETCH_POLICY_BY_ID_SUCCESS:
    OVERTIME_LOGGING_CONSTANTS.SUCCESS.FETCH_POLICY_BY_ID_SUCCESS,
  FETCH_POLICY_BY_ID_FAILED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.FETCH_POLICY_BY_ID_FAILED,
  FETCH_NEXT_PAGE_SUCCESS:
    OVERTIME_LOGGING_CONSTANTS.SUCCESS.FETCH_NEXT_PAGE_SUCCESS,
  FETCH_NEXT_PAGE_FAILED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.FETCH_NEXT_PAGE_FAILED,
  FETCH_PREVIOUS_PAGE_SUCCESS:
    OVERTIME_LOGGING_CONSTANTS.SUCCESS.FETCH_PREVIOUS_PAGE_SUCCESS,
  FETCH_PREVIOUS_PAGE_FAILED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.FETCH_PREVIOUS_PAGE_FAILED,
  FETCH_SPECIFIC_PAGE_SUCCESS:
    OVERTIME_LOGGING_CONSTANTS.SUCCESS.FETCH_SPECIFIC_PAGE_SUCCESS,
  FETCH_SPECIFIC_PAGE_FAILED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.FETCH_SPECIFIC_PAGE_FAILED,
  FETCH_WORKER_COUNT_FAILED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.FETCH_WORKER_COUNT_FAILED,
  ASSIGN_WORKERS_CLICKED:
    OVERTIME_LOGGING_CONSTANTS.USER_INTERACTIONS.ASSIGN_WORKERS_CLICKED,
  WIZARD_EDIT_MODE_MISSING_POLICY_ID:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.WIZARD_EDIT_MODE_MISSING_POLICY_ID,
  APOLLO_CLIENT_NOT_INITIALIZED:
    OVERTIME_LOGGING_CONSTANTS.API_ERRORS.APOLLO_CLIENT_NOT_INITIALIZED,

  // Wizard Funnel
  WIZARD_STEP_1_ENTERED:
    OVERTIME_LOGGING_CONSTANTS.WIZARD_FUNNEL.STEP_1_ENTERED,
  WIZARD_STEP_2_ENTERED:
    OVERTIME_LOGGING_CONSTANTS.WIZARD_FUNNEL.STEP_2_ENTERED,
  WIZARD_STEP_3_ENTERED:
    OVERTIME_LOGGING_CONSTANTS.WIZARD_FUNNEL.STEP_3_ENTERED,
  WIZARD_STEP_4_ENTERED:
    OVERTIME_LOGGING_CONSTANTS.WIZARD_FUNNEL.STEP_4_ENTERED,
  WIZARD_STEP_1_COMPLETED:
    OVERTIME_LOGGING_CONSTANTS.WIZARD_FUNNEL.STEP_1_COMPLETED,
  WIZARD_STEP_2_COMPLETED:
    OVERTIME_LOGGING_CONSTANTS.WIZARD_FUNNEL.STEP_2_COMPLETED,
  WIZARD_STEP_3_COMPLETED:
    OVERTIME_LOGGING_CONSTANTS.WIZARD_FUNNEL.STEP_3_COMPLETED,
  WIZARD_COMPLETED: OVERTIME_LOGGING_CONSTANTS.WIZARD_FUNNEL.WIZARD_COMPLETED,
  WIZARD_ABANDONED: OVERTIME_LOGGING_CONSTANTS.WIZARD_FUNNEL.WIZARD_ABANDONED,

  // Rule Type Selection
  RULE_TYPE_BASIC_SELECTED: OVERTIME_LOGGING_CONSTANTS.RULE_TYPE.BASIC_SELECTED,
  RULE_TYPE_CALIFORNIA_SELECTED:
    OVERTIME_LOGGING_CONSTANTS.RULE_TYPE.CALIFORNIA_SELECTED,
  RULE_TYPE_CUSTOM_SELECTED:
    OVERTIME_LOGGING_CONSTANTS.RULE_TYPE.CUSTOM_SELECTED,
} as const;
