import {
  IconSize,
  MenuButtonPriority,
  MenuButtonPurpose,
} from 'src/js/widgets/timeTrackingSettings/constants';

// This object containing the time settings fields which we use to showcase on the view screen
export const GENERAL_VIEW_FORM_CONFIG = {
  'time-settings.section.title.general': [
    {
      id: 'timeTrackingGeneral',
      key: 'generalTracking',
      title: 'location-settings.fields.general-settings',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isVisible: true,
    },
  ],
  'time-settings.section.title.timesheet': [
    {
      id: 'timeTrackingTimeSheetService',
      key: 'timesheetTrackingService',
      title: 'location-settings.fields.timesheet-settings-service',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isVisible: true,
    },
    {
      id: 'timeTrackingTimeSheetBillable',
      key: 'timesheetTrackingBillable',
      title: 'location-settings.fields.timesheet-settings-billable',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isVisible: true,
    },
  ],
};

// This object containing the time entry settings fields which we use to showcase on the view screen
export const TIME_TRACKING_FORM_CONFIG = {
  'time-entries.section.title.time-tracking': [
    {
      id: 'timeEntriesTimeTrackingManagement',
      key: 'timeEntryTimeTrackingManagement',
      title: 'time-entries.section.title.time-management',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: false,
      isVisible: true,
      automationId: 'tt-ts-management',
    },
    {
      id: 'timeEntriesFirstDayOfWeek',
      key: 'firstDayOfWeek',
      title: 'location-settings.fields.general-settings',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'first-day-work-week',
    },
    {
      id: 'timeEntriesTimeZone',
      key: 'timeZone',
      title: 'time-entries.section.title.time-management.time-zone',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'tt-time-zone',
    },
    {
      id: 'timeEntriesSplitTimesheetsAtMidnight',
      key: 'splitTimeSheetAtMidnightEnabled',
      title: 'time-entries.section.title.time-management.split-time-sheet',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'split-ts',
    },
    {
      id: 'timeEntriesAllowTeamMemberToAddAndEditTimeSheets',
      key: 'manageOwnTimeSheetsEnabled',
      title:
        'time-entries.section.title.time-management.allow-team-member-to-add-and-edit-time-sheet',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'allow-to-create-edit-ts',
    },
    {
      id: 'timeEntriesMobileTimeTrackingEnabled',
      key: 'mobileTimeTrackingEnabled',
      title:
        'time-entries.section.title.time-management.allow-team-member-to-track-time-on-mobile',
      ariaLabel:
        'time-entries.time-tracking.allow-team-member-to-track-time-on-mobile-popover',
      tooltipText:
        'time-entries.time-tracking.allow-team-member-to-track-time-on-mobile-popover',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'mobile-time-tracking',
    },
    {
      id: 'timeEntriesSignatureCaptureEnabled',
      key: 'signatureCaptureEnabled',
      title:
        'time-entries.section.title.time-management.capture-signatures-for-timesheets',
      ariaLabel:
        'time-entries.time-tracking.capture-signatures-for-timesheets-popover',
      tooltipText:
        'time-entries.time-tracking.capture-signatures-for-timesheets-popover',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'signature-capture',
    },
    {
      id: 'timeEntriesAllowTeamMemberToEditClockOutTime',
      key: 'editClockOutTimeEnabled',
      title:
        'time-entries.section.title.time-management.allow-team-member-to-edit-clock-out-time',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'allow-to-edit-clk-out',
    },
    {
      id: 'timeEntriesTimesheetRounding',
      key: 'timesheetRounding',
      title: 'time-entries.section.title.timesheet-rounding',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: false,
      isVisible: true,
      automationId: 'tt-ts-rounding',
    },
    {
      id: 'timeEntriesRoundClockInTimes',
      key: 'roundClockInTime',
      title:
        'time-entries.section.title.timesheet-rounding.round-clock-in-times',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'round-clk-in',
    },
    {
      id: 'timeEntriesRoundClockOutTimes',
      key: 'roundClockOutTime',
      title:
        'time-entries.section.title.timesheet-rounding.round-clock-out-times',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'round-clk-out',
    },
  ],
  'time-entries.section.title.time-sheet': [
    {
      id: 'timeSheetConfigureWhatYourTeamTrack',
      key: 'configureWhatYourTeamTrack',
      title:
        'time-entries.section.title.time-sheet.configure-what-your-team-track',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
    },
  ],
  'time-entries.section.title.notifications': [
    {
      id: 'notificationTimeEntriesNotificationManagement',
      key: 'notificationTimeEntriesNotificationManagement',
      title: 'time-entries.section.title.time-tracking',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: false,
      isVisible: true,
      automationId: 'notif-time-tracking',
    },
    {
      id: 'timeEntriesSendClockInReminders',
      key: 'sendClockInNotificationReminders',
      title:
        'time-entries.section.title.notifications.time-tracking.send-clock-in-reminders',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'clk-in-reminder',
    },
    {
      id: 'timeEntriesSendClockOutReminders',
      key: 'sendClockOutNotificationReminders',
      title:
        'time-entries.section.title.notifications.time-tracking.send-clock-out-reminders',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'clk-out-reminder',
    },
    {
      id: 'daysRemindersAreSend',
      key: 'notificationEnabledForDays',
      title:
        'time-entries.section.title.notifications.time-tracking.days-reminders-are-sent',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'days-of-week',
    },
    {
      id: 'notifyWhenClockInOutUpdated',
      key: 'notifyWhenClockInOutUpdated',
      title:
        'time-entries.section.title.notifications.time-tracking.notify-when-clock-in-out-is-adjusted',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'clk-in-out-adjust',
    },
    {
      id: 'notifyWhenNotesAreAddedOrEdited',
      key: 'notifyWhenNotesAreAddedOrEdited',
      title:
        'time-entries.section.title.notifications.time-tracking.notify-when-notes-are-added-or-edited',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'notes-add-adjust',
    },
    {
      id: 'scheduleSectionHeader',
      key: 'scheduleSectionHeader',
      title: 'time-entries.section.title.notifications.schedule',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: false,
      isVisible: true,
      automationId: 'notifications-schedule-section-header',
    },
    {
      id: 'scheduleShiftPublishedSendMode',
      key: 'shiftPublishedSendMode',
      title:
        'time-entries.section.title.notifications.schedule.shift-published-or-changed',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'notifications-schedule-shift-published',
    },
    {
      id: 'scheduleOneHourBeforeShift',
      key: 'scheduleOneHourBeforeShift',
      title:
        'time-entries.section.title.notifications.schedule.one-hour-before-shift',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'notifications-schedule-one-hour-before',
    },
    {
      id: 'scheduleForgotClockInAfterShiftStarted',
      key: 'scheduleForgotClockInAfterShiftStarted',
      title:
        'time-entries.section.title.notifications.schedule.forgot-clock-in-after-shift-started',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'notifications-schedule-forgot-clock-in-after-start',
    },
    {
      id: 'scheduleForgotClockInAfterShiftEnded',
      key: 'scheduleForgotClockInAfterShiftEnded',
      title:
        'time-entries.section.title.notifications.schedule.forgot-clock-out-after-shift-ended',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'notifications-schedule-forgot-clock-in-after-end',
    },
    {
      id: 'scheduleLateClockInNotifyManager',
      key: 'scheduleLateClockInNotifyManager',
      title:
        'time-entries.section.title.notifications.schedule.late-clock-in-notify-manager',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'notifications-schedule-late-clock-in-manager',
    },
    {
      id: 'approvalsSectionHeader',
      key: 'approvalsSectionHeader',
      title: 'time-entries.section.title.approvals',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: false,
      isVisible: true,
      automationId: 'approvals-section-header',
    },
    {
      id: 'remindManagersApproveTime',
      key: 'managerReminderBasedOn',
      title:
        'time-entries.section.title.approvals.remind-managers-approve-time',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '', // Will be updated dynamically
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'remind-managers-approve-time',
    },
    {
      id: 'remindIfTimeNotApproved',
      key: 'remindIfTimeNotApproved',
      title: 'time-entries.section.title.approvals.remind-if-time-not-approved',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '', // Will be updated dynamically
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'remind-if-time-not-approved',
    },
    {
      id: 'remindSecondTimeNotApproved',
      key: 'remindSecondTimeNotApproved',
      title:
        'time-entries.section.title.approvals.remind-second-time-not-approved',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '', // Will be updated dynamically
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'remind-second-time-not-approved',
    },
    {
      id: 'submissionsSectionHeader',
      key: 'submissionsSectionHeader',
      title: 'time-entries.section.title.submissions',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: false,
      isVisible: true,
      automationId: 'submissions-section-header',
    },
    {
      id: 'employeeReminderBasedOn',
      key: 'employeeReminderBasedOn',
      title:
        'time-entries.section.title.submissions.send-reminder-team-submit-time',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '', // Will be updated dynamically
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'send-reminder-team-submit-time',
    },
    {
      id: 'employeeDailyReminderForTimesheetDays',
      key: 'employeeDailyReminderForTimesheetDays',
      title:
        'time-entries.section.title.notifications.time-tracking.days-reminders-are-sent',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '', // Will be updated dynamically
      subFields: [],
      isEditable: true,
      isVisible: false, // Only visible when DAILY
      automationId: 'submission-reminder-days-of-week',
    },
    {
      id: 'remindIfTimeNotSubmitted',
      key: 'remindIfTimeNotSubmitted',
      title:
        'time-entries.section.title.submissions.remind-if-time-not-submitted',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '', // Will be updated dynamically
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'remind-if-time-not-submitted',
    },
    {
      id: 'remindSecondTimeNotSubmitted',
      key: 'remindSecondTimeNotSubmitted',
      title:
        'time-entries.section.title.submissions.remind-second-time-not-submitted',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '', // Will be updated dynamically
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'remind-second-time-not-submitted',
    },
    {
      id: 'notifyManagerOnSubmit',
      key: 'notifyManagerOnSubmit',
      title:
        'time-entries.section.title.submissions.email-managers-team-member-submits',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '', // Will be updated dynamically
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'email-managers-entire-team-submits',
    },
    {
      id: 'notifyManagerOnGroupSubmitted',
      key: 'notifyManagerOnGroupSubmitted',
      title:
        'time-entries.section.title.submissions.email-managers-entire-team-submits',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '', // Will be updated dynamically
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'email-managers-team-member-submits',
    },
    {
      id: 'geofenceSettingsHeader',
      key: 'geofenceSettingsHeader',
      title: 'time-entries.section.title.notifications.geofence',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: false,
      isVisible: true,
      automationId: 'geofence-settings-header',
    },
    {
      id: 'geofenceReminderSettings',
      key: 'geofenceReminderSettings',
      title:
        'time-entries.section.title.notifications.geofence.send-reminder-to-team',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'geofence-reminder-settings',
    },
  ],
  'time-entries.section.title.custom-fields': [
    {
      id: 'timeEntriesCustomFields',
      key: 'customFields',
      title: 'time-entries.section.title.custom-fields.title',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'time-entries-custom-fields',
    },
    {
      id: 'timeEntriesCustomFieldsButton',
      key: 'customFieldsButton',
      title: '',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: true,
      isVisible: true,
      automationId: 'time-entries-custom-fields-button',
      /**
       * This is optional field which will be used to show the menu button in settings.
       * Add this to config if you want to show the menu button.
       */
      menuButton: {
        label: 'time-entries.section.title.custom-fields.add-custom-field',
        onClick: () => {
          // This will be handled by the parent component to show drawer
        },
        automationId: 'add-new-custom-field-button',
        icon: 'manage',
        iconSize: IconSize.SMALL,
        priority: MenuButtonPriority.TERTIARY,
        purpose: MenuButtonPurpose.STANDARD,
        size: IconSize.SMALL,
      },
    },
  ],
};

// This object containing the custom time sheet fields which we use to showcase on the view screen
export const TIMESHEET_SETTINGS_FIELDS = [
  {
    id: 'shareCustomers',
    key: 'customersForTimeSheetEnabled',
    title: 'time-entries.section.title.time-sheet.customer-and-sub-customer',
    ariaLabel: '',
    tooltipText: '',
    detail: {
      title:
        'time-entries.section.title.time-sheet.mobile-preview.item.customers.title',
      subtitle:
        'time-entries.section.title.time-sheet.mobile-preview.item.customers.subtitle',
      ariaLabel: '',
    },
    disabled: true,
    value: false,
    automationId: 'cust-cust-subcust',
    requiredField: {
      id: 'customersRequired',
      key: 'customersRequired',
      disabled: false,
      value: false,
    },
  },
  {
    id: 'service',
    key: 'isServiceFieldEnabled',
    title: 'time-entries.section.title.time-sheet.service-item',
    ariaLabel: '',
    tooltipText: '',
    detail: {
      title:
        'time-entries.section.title.time-sheet.mobile-preview.item.service-item.title',
      subtitle:
        'time-entries.section.title.time-sheet.mobile-preview.item.service-item.subtitle',
      ariaLabel: '',
    },
    disabled: false,
    value: false,
    automationId: 'cust-service-item',
    requiredField: {
      id: 'serviceItemRequired',
      key: 'serviceItemRequired',
      disabled: false,
      value: false,
    },
  },
  {
    id: 'showBillable',
    key: 'isBillingFieldEnabled',
    title: 'time-entries.section.title.time-sheet.billable',
    ariaLabel: '',
    tooltipText: 'time-entries.section.title.time-sheet.billable.tool-tip',
    detail: {
      title:
        'time-entries.section.title.time-sheet.mobile-preview.item.billable.title',
      subtitle:
        'time-entries.section.title.time-sheet.mobile-preview.item.billable.subtitle',
      ariaLabel: '',
    },
    disabled: false,
    value: false,
    automationId: 'cust-billable',
    subFields: [
      {
        id: 'ratePerHour',
        key: 'billingRateForTimeEnabled',
        title: 'time-entries.section.title.time-sheet.billable.rate-per-hour',
        ariaLabel: '',
        tooltipText:
          'time-entries.section.title.time-sheet.billable.rate-per-hour.tool-tip',
        detail: {
          title:
            'time-entries.section.title.time-sheet.mobile-preview.item.billable.rate-per-hour',
          subtitle:
            'time-entries.section.title.time-sheet.mobile-preview.item.billable.rate-per-hour.subtitle',
          ariaLabel: '',
        },
        disabled: false,
        value: false,
        automationId: 'cust-rate-per-hour',
      },
      {
        id: 'requireBillable',
        key: 'requireBillable',
        title:
          'time-entries.section.title.time-sheet.billable.require-billable',
        ariaLabel: '',
        tooltipText: '',
        detail: {
          title:
            'time-entries.section.title.time-sheet.mobile-preview.item.billable.require-billable',
          subtitle:
            'time-entries.section.title.time-sheet.mobile-preview.item.billable.require-billable.subtitle',
          ariaLabel: '',
        },
        disabled: false,
        value: false,
        automationId: 'cust-require-billable',
      },
    ],
    requiredField: {
      id: 'requireBillable',
      key: 'requireBillable',
      disabled: false,
      value: false,
    },
  },
  {
    id: 'class',
    key: 'classForTimeSheetEnabled',
    title: 'time-entries.section.title.time-sheet.class',
    ariaLabel: '',
    tooltipText: '',
    detail: {
      title:
        'time-entries.section.title.time-sheet.mobile-preview.item.class.title',
      subtitle:
        'time-entries.section.title.time-sheet.mobile-preview.item.class.subtitle',
      ariaLabel: '',
    },
    disabled: false,
    value: false,
    automationId: 'cust-class',
    requiredField: {
      id: 'classRequired',
      key: 'classRequired',
      disabled: false,
      value: false,
    },
  },
  {
    id: 'location',
    key: 'locationForTimeSheetEnabled',
    title: 'time-entries.section.title.time-sheet.location',
    ariaLabel: '',
    tooltipText: '',
    detail: {
      title:
        'time-entries.section.title.time-sheet.mobile-preview.item.location.title',
      subtitle:
        'time-entries.section.title.time-sheet.mobile-preview.item.location.subtitle',
      ariaLabel: '',
    },
    disabled: false,
    value: false,
    automationId: 'cust-location',
    requiredField: {
      id: 'locationRequired',
      key: 'locationRequired',
      disabled: false,
      value: false,
    },
  },
  {
    id: 'notes',
    key: 'timeSheetEntryNotesEnabled',
    title: 'time-entries.section.title.time-sheet.notes',
    ariaLabel: '',
    tooltipText: '',
    detail: {
      title:
        'time-entries.section.title.time-sheet.mobile-preview.item.notes.title',
      subtitle:
        'time-entries.section.title.time-sheet.mobile-preview.item.notes.placeholder',
      ariaLabel: '',
      automationId: 'cust-notes',
    },
    disabled: false,
    value: false,
    subFields: [
      {
        id: 'allowTeamMemberToEditExistingNotes',
        key: 'timeSheetEntryEditNotesEnabled',
        title:
          'time-entries.section.title.time-sheet.notes.allow-team-member-to-edit-existing-notes',
        ariaLabel: '',
        tooltipText: '',
        detail: {
          title: '',
          subtitle: '',
          ariaLabel: '',
        },
        disabled: false,
        value: false,
        automationId: 'cust-allow-edit-note',
      },
      {
        id: 'requireNotes',
        key: 'timeSheetEntryMakesNotesRequiredEnabled',
        title: 'time-entries.section.title.time-sheet.billable.require-notes',
        ariaLabel: '',
        tooltipText: '',
        detail: {
          title: '',
          subtitle: '',
          ariaLabel: '',
        },
        disabled: false,
        value: false,
        automationId: 'require-notes',
      },
    ],
    requiredField: {
      id: 'requireNotes',
      key: 'timeSheetEntryMakesNotesRequiredEnabled',
      disabled: false,
      value: false,
    },
  },
];

// Approval settings field definitions (template)
export const APPROVAL_SETTINGS_CONFIG = {
  'time-entries.section.title.approvals': [
    {
      id: 'approvalsRequired',
      key: 'approvalsRequired',
      title: 'time-entries.section.title.approvals.approval-installed',
      subtitle:
        'time-entries.section.title.approvals.require-approval-for-tracked-time.subtitle',
      automationId: 'install-approval',
      value: 'On',
      isEditable: true,
      isVisible: true,
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      subFields: [],
    },
    {
      id: 'timeEntriesRequireApprovalForTrackedTime',
      key: 'requireApprovalForTrackedTime',
      title:
        'time-entries.section.title.approvals.require-approval-for-tracked-time',
      subtitle: '',
      automationId: 'require-approval-for-tracked-time',
      value: '',
      isEditable: true,
      isVisible: true,
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      subFields: [],
    },
    {
      id: 'timeEntriesPartialWeekApproval',
      key: 'enablePartialWeekSubmission',
      title:
        'time-entries.section.title.approvals.require-submission-for-full-week',
      automationId: 'partial-week-approval',
      value: '',
      isEditable: true,
      isVisible: true,
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      subFields: [],
    },
    {
      id: 'timeEntriesRequireTeamMembersSubmitTime',
      key: 'requireTeamMembersSubmitTime',
      title:
        'time-entries.section.title.approvals.require-team-members-submit-time',
      automationId: 'require-team-members-submit-time',
      value: '',
      isEditable: true,
      isVisible: true,
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      subFields: [],
    },
    {
      id: 'timeEntriesCustomMessage',
      key: 'customMessage',
      title: 'time-entries.section.title.approvals.custom-message',
      automationId: 'custom-message',
      value: '',
      isEditable: true,
      isVisible: true,
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      subFields: [],
    },
  ],
};

// Geo locations settings field definitions (template)
export const GEO_LOCATIONS_SETTINGS_CONFIG = {
  'time-entries.section.title.geo-locations': [
    {
      id: 'geoLocationTracking',
      key: 'locationTracking',
      title: 'time-entries.section.title.geo-locations.location-tracking',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isVisible: true,
    },
    {
      id: 'timeEntriesMileageTracking',
      key: 'mileageTracking',
      title: 'time-entries.section.title.geo-locations.mileage-tracking',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isVisible: true,
    },
    {
      id: 'timeEntriesGeofence',
      key: 'geofence',
      title: 'time-entries.section.title.geo-locations.geofencing',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isVisible: true,
    },
  ],
};

// Schedule settings field definitions (template)
export const SCHEDULE_SETTINGS_CONFIG = {
  'time-entries.section.title.schedules': [
    {
      id: 'schedulesPreferencesHeader',
      key: 'schedulesPreferencesHeader',
      title: 'time-entries.section.title.schedules.preferences',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isEditable: false,
      isVisible: true,
      automationId: 'schedules-preferences-header',
    },
    {
      id: 'scheduleViewSchedule',
      key: 'viewSchedule',
      title: 'time-entries.section.title.schedules.view-schedule',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isVisible: true,
      automationId: 'schedules-view-schedule',
    },
    {
      id: 'scheduleManageSchedule',
      key: 'manageSchedule',
      title: 'time-entries.section.title.schedules.manage-schedule',
      ariaLabel: '',
      tooltipText: '',
      detail: {
        title: '',
        subtitle: '',
        ariaLabel: '',
      },
      disabled: false,
      value: '',
      subFields: [],
      isVisible: true,
      automationId: 'schedules-manage-schedule',
    },
  ],
};
