const OVERTIME_SETTINGS_PREFIX = 'OvertimeSettings';
const SCHEDULE_NOTIFICATIONS_PREFIX = 'ScheduleNotifications';
const OVERTIME_NOTIFICATIONS_PREFIX = 'OvertimeNotifications';

/**
 * Flat logging constants for UserSettings Overtime Policy.
 * Only export constants that are actively used in the codebase.
 */
export const USER_SETTINGS_OVERTIME_LOGGING = {
  // Navigation / Lifecycle
  CARD_VIEW_MOUNTED: `${OVERTIME_SETTINGS_PREFIX}.CARD_VIEW_MOUNTED`,
  CARD_EDIT_MOUNTED: `${OVERTIME_SETTINGS_PREFIX}.CARD_EDIT_MOUNTED`,
  NAVIGATION_FAILED: `${OVERTIME_SETTINGS_PREFIX}.NAVIGATION_FAILED`,
  FETCH_POLICY_REQUESTED: `${OVERTIME_SETTINGS_PREFIX}.FETCH_POLICY_REQUESTED`,

  // User Interactions
  EDIT_CLICKED: `${OVERTIME_SETTINGS_PREFIX}.EDIT_CLICKED`,
  NAVIGATE_TO_POLICY_DETAILS_CLICKED: `${OVERTIME_SETTINGS_PREFIX}.NAVIGATE_TO_POLICY_DETAILS_CLICKED`,
  NAVIGATE_TO_TIME_SETTINGS_CLICKED: `${OVERTIME_SETTINGS_PREFIX}.NAVIGATE_TO_TIME_SETTINGS_CLICKED`,
  SAVE_CLICKED: `${OVERTIME_SETTINGS_PREFIX}.SAVE_CLICKED`,
  CANCEL_CLICKED: `${OVERTIME_SETTINGS_PREFIX}.CANCEL_CLICKED`,
  RADIO_COMPANY_SELECTED: `${OVERTIME_SETTINGS_PREFIX}.RADIO_COMPANY_SELECTED`,
  RADIO_CUSTOM_SELECTED: `${OVERTIME_SETTINGS_PREFIX}.RADIO_CUSTOM_SELECTED`,
  DELETE_CONFIRM_SHOWN: `${OVERTIME_SETTINGS_PREFIX}.DELETE_CONFIRM_SHOWN`,
  DELETE_CONFIRM_CANCELLED: `${OVERTIME_SETTINGS_PREFIX}.DELETE_CONFIRM_CANCELLED`,
  DELETE_CONFIRMED: `${OVERTIME_SETTINGS_PREFIX}.DELETE_CONFIRMED`,
  RULE_TYPE_CHANGED: `${OVERTIME_SETTINGS_PREFIX}.RULE_TYPE_CHANGED`,
  MANAGE_COMPANY_POLICIES_CLICKED: `${OVERTIME_SETTINGS_PREFIX}.MANAGE_COMPANY_POLICIES_CLICKED`,
  CHECK_LAWS_LINK_CLICKED: `${OVERTIME_SETTINGS_PREFIX}.CHECK_LAWS_LINK_CLICKED`,

  // API Success
  FETCH_POLICY_SUCCESS: `${OVERTIME_SETTINGS_PREFIX}.FETCH_POLICY_SUCCESS`,
  CREATE_POLICY_SUCCESS: `${OVERTIME_SETTINGS_PREFIX}.CREATE_POLICY_SUCCESS`,
  UPDATE_POLICY_SUCCESS: `${OVERTIME_SETTINGS_PREFIX}.UPDATE_POLICY_SUCCESS`,
  DELETE_POLICY_SUCCESS: `${OVERTIME_SETTINGS_PREFIX}.DELETE_POLICY_SUCCESS`,

  // API Errors
  FETCH_POLICY_FAILED: `${OVERTIME_SETTINGS_PREFIX}.FETCH_POLICY_FAILED`,
  APOLLO_CLIENT_NOT_INITIALIZED: `${OVERTIME_SETTINGS_PREFIX}.APOLLO_CLIENT_NOT_INITIALIZED`,
  CREATE_POLICY_FAILED: `${OVERTIME_SETTINGS_PREFIX}.CREATE_POLICY_FAILED`,
  UPDATE_POLICY_FAILED: `${OVERTIME_SETTINGS_PREFIX}.UPDATE_POLICY_FAILED`,
  DELETE_POLICY_FAILED: `${OVERTIME_SETTINGS_PREFIX}.DELETE_POLICY_FAILED`,
  MISSING_SETTINGS_FOR_ID: `${OVERTIME_SETTINGS_PREFIX}.MISSING_SETTINGS_FOR_ID`,
  SAVE_FAILED: `${OVERTIME_SETTINGS_PREFIX}.SAVE_FAILED`,
} as const;

/**
 * Flat logging constants for UserSettings Schedule Notifications.
 * Only export constants that are actively used in the codebase.
 */
export const USER_SETTINGS_SCHEDULE_NOTIFICATIONS_LOGGING = {
  FETCH_RULES_SUCCESS: `${SCHEDULE_NOTIFICATIONS_PREFIX}.FETCH_RULES_SUCCESS`,
  FETCH_RULES_FAILED: `${SCHEDULE_NOTIFICATIONS_PREFIX}.FETCH_RULES_FAILED`,
  SAVE_SUCCESS: `${SCHEDULE_NOTIFICATIONS_PREFIX}.SAVE_SUCCESS`,
  SAVE_FAILED: `${SCHEDULE_NOTIFICATIONS_PREFIX}.SAVE_FAILED`,
} as const;

/**
 * Flat logging constants for UserSettings Overtime Notifications.
 * Only export constants that are actively used in the codebase.
 */
export const USER_SETTINGS_OVERTIME_NOTIFICATIONS_LOGGING = {
  // Navigation / Lifecycle
  VIEW_MOUNTED: `${OVERTIME_NOTIFICATIONS_PREFIX}.VIEW_MOUNTED`,
  EDIT_MOUNTED: `${OVERTIME_NOTIFICATIONS_PREFIX}.EDIT_MOUNTED`,

  // User Interactions
  DAILY_PANEL_TOGGLED: `${OVERTIME_NOTIFICATIONS_PREFIX}.DAILY_PANEL_TOGGLED`,
  WEEKLY_PANEL_TOGGLED: `${OVERTIME_NOTIFICATIONS_PREFIX}.WEEKLY_PANEL_TOGGLED`,

  // API Success / Errors
  FETCH_RULES_SUCCESS: `${OVERTIME_NOTIFICATIONS_PREFIX}.FETCH_RULES_SUCCESS`,
  FETCH_RULES_FAILED: `${OVERTIME_NOTIFICATIONS_PREFIX}.FETCH_RULES_FAILED`,
} as const;
