import { TrackingPoint } from '../../common/useClickTracking';

/**
 * Time Entry Settings Tracking Point Interface
 * Extends the base TrackingPoint to ensure type safety for time entry settings events
 */
export interface TimeEntrySettingsTrackingPoint extends TrackingPoint {}

/**
 * Time Entry Settings Tracking Points Interface
 * Defines the structure for all time entry settings tracking events
 */
export interface TimeEntrySettingsTrackingPoints {
  [key: string]: TimeEntrySettingsTrackingPoint;
}

/**
 * Assigned To Types for Standard Field Assignment Tracking
 * Used as a dynamic parameter in tracking events
 */
export type AssignedToType =
  | 'custom_field'
  | 'standard_field'
  | 'standard_field_item';

/**
 * Standard Field Assignment Tracking Point Interface
 * Extends the base tracking point with an optional assigned_to parameter
 */
export interface StandardFieldAssignmentTrackingPoint
  extends TimeEntrySettingsTrackingPoint {
  assigned_to?: AssignedToType;
}

/**
 * Base configuration for all standard field assignments tracking points
 */
const STANDARD_FIELD_ASSIGNMENTS_BASE_CONFIG = {
  org: 'sbseg',
  purpose: 'prod',
  scope: 'time',
  scope_area: 'timeentrymanagement',
  screen: 'assignments',
  object: 'component',
  object_detail: 'assign_customers',
} as const;

/**
 * STANDARD_FIELD_ASSIGNMENTS_TRACKING_POINTS
 *
 * Analytics tracking points for Standard Field Customer/Worker Assignment feature
 * Includes all user interactions within the assignment drawers
 *
 * Event parameter: assigned_to - should be set dynamically based on context:
 * - 'custom_field': When assigning from custom field context
 * - 'standard_field': When assigning from standard field (e.g., Service, Class, Location)
 * - 'standard_field_item': When assigning from a specific standard field option/item
 */
export const STANDARD_FIELD_ASSIGNMENTS_TRACKING_POINTS: {
  [key: string]: StandardFieldAssignmentTrackingPoint;
} = {
  // View Customer Assignment Drawer
  VIEW_CUSTOMER_ASSIGNMENT_DRAWER: {
    ...STANDARD_FIELD_ASSIGNMENTS_BASE_CONFIG,
    action: 'viewed',
    ui_action: 'viewed',
    ui_object: 'drawer',
    ui_object_detail: 'assign_customers',
  },

  // View Worker Assignment Drawer
  VIEW_WORKER_ASSIGNMENT_DRAWER: {
    ...STANDARD_FIELD_ASSIGNMENTS_BASE_CONFIG,
    object_detail: 'assign_workers',
    action: 'viewed',
    ui_action: 'viewed',
    ui_object: 'drawer',
    ui_object_detail: 'assign_workers',
  },

  // Typing in search field in assignment drawer
  SEARCH_FIELDS_IN_ASSIGNMENT_DRAWER: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'standard_field_detail_page',
    action: 'engaged',
    object: 'component',
    object_detail: 'add_standard_field_item',
    ui_action: 'typed',
    ui_object: 'form_field',
    ui_object_detail: 'search',
  },

  // Typing in search customers in assignment drawer
  SEARCH_CUSTOMERS_ASSIGNMENT_DRAWER: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'assignments',
    action: 'engaged',
    object: 'component',
    object_detail: 'assign_customers',
    ui_action: 'typed',
    ui_object: 'form_field',
    ui_object_detail: 'search',
  },

  // Save customer/worker assignments to fields
  SAVE_ASSIGNMENTS: {
    ...STANDARD_FIELD_ASSIGNMENTS_BASE_CONFIG,
    action: 'engaged',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'save',
  },

  // Cancel "X" customer/worker assignments to fields
  CANCEL_ASSIGNMENTS: {
    ...STANDARD_FIELD_ASSIGNMENTS_BASE_CONFIG,
    action: 'engaged',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'X',
  },

  // View Standard Field detail page
  VIEW_STANDARD_FIELD: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'standard_field_settings',
    action: 'engaged',
    object: 'component',
    object_detail: 'timesheet_standard_fields',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'view',
  },

  // Standard Field: Add item
  ADD_STANDARD_FIELD_ITEM: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'standard_field_detail_page',
    action: 'engaged',
    object: 'component',
    object_detail: 'add_standard_field_item',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'add_standard_field_item',
  },
};

/**
 * TIME_ENTRY_SETTINGS_TRACKING_POINTS
 *
 * Analytics tracking points for Time Entry Settings feature
 * Includes all user interactions within the time entry settings page
 */
export const TIME_ENTRY_SETTINGS_TRACKING_POINTS: TimeEntrySettingsTrackingPoints =
  {
    ON_MOUNT: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'navigated',
      object: 'drawer',
      object_detail: 'view_time_entry_settings',
      ui_action: 'viewed',
      ui_object: 'page',
      ui_object_detail: 'view_time_entry_settings',
      ui_access_point: 'page',
    },
    TIME_TRACKING_SECTION_SAVE: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'time_tracking_section_save',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_object_detail: 'time_tracking_section_save',
      ui_access_point: 'page',
    },
    TIME_TRACKING_SECTION_EDIT: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'time_tracking_section_edit',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_object_detail: 'time_tracking_section_edit',
      ui_access_point: 'page',
    },
    // Need to get the name confirmed
    TIMESHEET_FIELDS_SECTION_SAVE: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_section_save',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_object_detail: 'timesheet_fields_section_save',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_SECTION_EDIT: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_section_edit',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_object_detail: 'timesheet_fields_section_edit',
      ui_access_point: 'page',
    },
    NOTIFICATION_SECTION_SAVE: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'notification_section_save',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_object_detail: 'notification_section_save',
      ui_access_point: 'page',
    },
    NOTIFICATION_SECTION_EDIT: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'notification_section_edit',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_object_detail: 'notification_section_edit',
      ui_access_point: 'page',
    },
    CUSTOM_FIELDS_SECTION: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'custom_fields_section',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_object_detail: 'custom_fields_section',
      ui_access_point: 'page',
    },
    MANAGE_ALL_CUSTOM_FIELDS: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'custom-field',
      screen: 'custom_fields_page',
      action: 'engaged',
      object: 'widget',
      object_detail: 'manage_all_custom_fields',
      ui_action: 'clicked',
      ui_object: 'link',
      ui_object_detail: 'manage_all_custom_fields',
      ui_access_point: 'page',
    },
    TIMESHEET_MANAGEMENT_FIRST_DAY_OF_WEEK: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_management_first_day_of_week',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'timesheet_management_first_day_of_week',
      ui_access_point: 'page',
    },
    TIMESHEET_MANAGEMENT_TIME_ZONE: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_management_time_zone',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'timesheet_management_time_zone',
      ui_access_point: 'page',
    },
    TIMESHEET_MANAGEMENT_TIME_FORMAT: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_management_time_format',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'timesheet_management_time_format',
      ui_access_point: 'page',
    },
    TIMESHEET_MANAGEMENT_SPLIT_AT_MIDNIGHT: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_management_split_at_midnight',
      ui_action: '', // enabled | disabled
      ui_object: 'checkbox',
      ui_object_detail: 'timesheet_management_split_at_midnight',
      ui_access_point: 'page',
    },
    TIMESHEET_MANAGEMENT_EDIT_OWN_TIMESHEET: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_management_edit_own_timesheet',
      ui_action: '', // enabled | disabled
      ui_object: 'checkbox',
      ui_object_detail: 'timesheet_management_edit_own_timesheet',
      ui_access_point: 'page',
    },
    TIMESHEET_MANAGEMENT_MOBILE_TIME_TRACKING: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_management_mobile_time_tracking',
      ui_action: '', // enabled | disabled
      ui_object: 'checkbox',
      ui_object_detail: 'timesheet_management_mobile_time_tracking',
      ui_access_point: 'page',
    },
    TIMESHEET_MANAGEMENT_SIGNATURE_CAPTURE: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_management_signature_capture',
      ui_action: '', // enabled | disabled
      ui_object: 'checkbox',
      ui_object_detail: 'timesheet_management_signature_capture',
      ui_access_point: 'page',
    },
    TIMESHEET_MANAGEMENT_EDIT_CLOCKOUT_OVERRIDE_HOURS: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_management_edit_clockout_override_hours',
      ui_action: 'typed',
      ui_object: 'textbox',
      ui_object_detail: 'timesheet_management_edit_clockout_override_hours',
      ui_access_point: 'page',
    },
    TIMESHEET_MANAGEMENT_EDIT_CLOCKOUT_OVERRIDE_ENABLED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_management_edit_clockout_override_enabled',
      ui_action: '', // enabled | disabled
      ui_object: 'checkbox',
      ui_object_detail: 'timesheet_management_edit_clockout_override_enabled',
      ui_access_point: 'page',
    },
    TIMESHEET_MANAGEMENT_CLOCK_IN_DIRECTION: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_management_clock_in_direction',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'timesheet_management_clock_in_direction',
      ui_access_point: 'page',
    },
    TIMESHEET_MANAGEMENT_CLOCK_OUT_DIRECTION: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_management_clock_out_direction',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'timesheet_management_clock_out_direction',
      ui_access_point: 'page',
    },
    TIMESHEET_MANAGEMENT_CLOCK_IN_INCREMENT: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_management_clock_in_increment',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'timesheet_management_clock_in_increment',
      ui_access_point: 'page',
    },
    TIMESHEET_MANAGEMENT_CLOCK_OUT_INCREMENT: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_management_clock_out_increment',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'timesheet_management_clock_out_increment',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_CUSTOMERS_AND_SUBCUSTOMERS: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_customers_and_subcustomers',
      ui_action: '', // enabled/disabled
      ui_object: 'checkbox',
      ui_object_detail: 'timesheet_fields_customers_and_subcustomers',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_CUSTOMERS_AND_SUBCUSTOMERS_REQUIRED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_customers_and_subcustomers_required',
      ui_action: '', // enabled/disabled
      ui_object: 'toggle',
      ui_object_detail: 'timesheet_fields_customers_and_subcustomers_required',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_SERVICE_ITEM: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_service_item',
      ui_action: '', // enabled/disabled
      ui_object: 'checkbox',
      ui_object_detail: 'timesheet_fields_service_item',
      ui_access_point: 'page',
    },
    TIME_SHEET_FIELD_SERVICE_ITEM_REQUIRED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_field_service_item_required',
      ui_action: '', // enabled/disabled
      ui_object: 'toggle',
      ui_object_detail: 'timesheet_field_service_item_required',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_BILLABLE: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_billable',
      ui_action: '', // enabled/disabled
      ui_object: 'checkbox',
      ui_object_detail: 'timesheet_fields_billable',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_RATE_PER_HOUR: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_rate_per_hour',
      ui_action: '', // enabled/disabled
      ui_object: 'checkbox',
      ui_object_detail: 'timesheet_fields_rate_per_hour',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_BILLABLE_REQUIRED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_billable_required',
      ui_action: '', // enabled/disabled
      ui_object: 'toggle',
      ui_object_detail: 'timesheet_fields_billable_required',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_CLASS: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_class',
      ui_action: '', // enabled/disabled
      ui_object: 'checkbox',
      ui_object_detail: 'timesheet_fields_class',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_CLASS_REQUIRED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_class_required',
      ui_action: '', // enabled/disabled
      ui_object: 'toggle',
      ui_object_detail: 'timesheet_fields_class_required',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_LOCATION: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_location',
      ui_action: '', // enabled/disabled
      ui_object: 'checkbox',
      ui_object_detail: 'timesheet_fields_location',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_LOCATION_REQUIRED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_location_required',
      ui_action: '', // enabled/disabled
      ui_object: 'toggle',
      ui_object_detail: 'timesheet_fields_location_required',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_NOTES: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_notes',
      ui_action: '',
      ui_object: 'checkbox',
      ui_object_detail: 'timesheet_fields_notes',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_MAKE_NOTES_REQUIRED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_make_notes_required',
      ui_action: '',
      ui_object: 'toggle', // enabled/disabled
      ui_object_detail: 'timesheet_fields_make_notes_required',
      ui_access_point: 'page',
    },
    TIMESHEET_FIELDS_EDIT_NOTES: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_edit_notes',
      ui_action: '',
      ui_object: 'checkbox',
      ui_object_detail: 'timesheet_fields_edit_notes',
      ui_access_point: 'page',
    },
    NOTIFICATION_CLOCK_IN_EMAIL: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'notification_clock_in_email',
      ui_action: '', // enabled | disabled
      ui_object: 'checkbox',
      ui_object_detail: 'notification_clock_in_email',
      ui_access_point: 'page',
    },
    NOTIFICATION_CLOCK_OUT_EMAIL: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'notification_clock_out_email',
      ui_action: '', // enabled | disabled
      ui_object: 'checkbox',
      ui_object_detail: 'notification_clock_out_email',
      ui_access_point: 'page',
    },
    NOTIFICATION_CLOCK_IN_MOBILE: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'notification_clock_in_mobile',
      ui_action: '', // enabled | disabled
      ui_object: 'checkbox',
      ui_object_detail: 'notification_clock_in_mobile',
      ui_access_point: 'page',
    },
    NOTIFICATION_CLOCK_OUT_MOBILE: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'notification_clock_out_mobile',
      ui_action: '',
      ui_object: 'checkbox',
      ui_object_detail: 'notification_clock_out_mobile',
      ui_access_point: 'page',
    },
    NOTIFICATION_NOTES_ADJUSTED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'notification_notes_adjusted',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'notification_notes_adjusted',
      ui_access_point: 'page',
    },
    NOTIFICATION_CLOCK_IN_OUT_ADJUSTED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'notification_clock_in_out_adjusted',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'notification_clock_in_out_adjusted',
      ui_access_point: 'page',
    },
    NOTIFICATION_DAYS_OF_WEEK: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'notification_days_of_week',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'notification_days_of_week',
      ui_access_point: 'page',
    },
    NOTIFICATION_CLOCK_IN_REMINDER_TIME: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'notification_clock_in_reminder_time',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'notification_clock_in_reminder_time',
      ui_access_point: 'page',
    },
    NOTIFICATION_CLOCK_OUT_REMINDER_TIME: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'notification_clock_out_reminder_time',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'notification_clock_out_reminder_time',
      ui_access_point: 'page',
    },
    GEOFENCE_REMINDER_START_TIME: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'geofence_reminder_start_time',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'geofence_reminder_start_time',
      ui_access_point: 'page',
    },
    GEOFENCE_REMINDER_END_TIME: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'geofence_reminder_end_time',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'geofence_reminder_end_time',
      ui_access_point: 'page',
    },
    GEOFENCE_REMINDER_DAYS_OF_WEEK: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'geofence_reminder_days_of_week',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'geofence_reminder_days_of_week',
      ui_access_point: 'page',
    },

    TIME_TRACKING_SECTION_CANCEL: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'time_tracking_section_cancel',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_access_point: 'page',
      ui_object_detail: 'time_tracking_section_cancel',
    },
    TIMESHEET_FIELDS_SECTION_CANCEL: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_section_cancel',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_access_point: 'page',
      ui_object_detail: 'timesheet_fields_section_cancel',
    },
    NOTIFICATION_SECTION_CANCEL: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'notification_section_cancel',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_access_point: 'page',
      ui_object_detail: 'notification_section_cancel',
    },
    GEO_LOCATIONS_SECTION_SAVE: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'geo_locations_section_save',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_object_detail: 'geo_locations_section_save',
      ui_access_point: 'page',
    },
    GEO_LOCATIONS_SECTION_EDIT: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'geo_locations_section_edit',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_object_detail: 'geo_locations_section_edit',
      ui_access_point: 'page',
    },
    GEO_LOCATIONS_TROWSER_VIEWED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'viewed',
      object: 'widget',
      object_detail: 'geo_locations_trowser',
      ui_action: 'viewed',
      ui_object: 'trowser',
      ui_access_point: 'trowser',
      ui_object_detail: 'geo_locations_trowser',
    },
    GEO_LOCATIONS_SECTION_CANCEL: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'geo_locations_section_cancel',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_access_point: 'page',
      ui_object_detail: 'geo_locations_section_cancel',
    },
    GEO_LOCATIONS_CARD_REQUIRED_CLICKED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'geo_locations_card_required',
      ui_action: 'clicked',
      ui_object: 'card',
      ui_access_point: 'trowser',
      ui_object_detail: 'geo_locations_card_required',
    },
    GEO_LOCATIONS_CARD_OPTIONAL_CLICKED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'geo_locations_card_optional',
      ui_action: 'clicked',
      ui_object: 'card',
      ui_access_point: 'trowser',
      ui_object_detail: 'geo_locations_card_optional',
    },
    GEO_LOCATIONS_CARD_NEVER_CLICKED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'geo_locations_card_never',
      ui_action: 'clicked',
      ui_object: 'card',
      ui_access_point: 'trowser',
      ui_object_detail: 'geo_locations_card_never',
    },
    GEO_LOCATIONS_MODAL_SAVE_CLICKED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'geo_locations_modal_save',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_access_point: 'modal',
      ui_object_detail: 'geo_locations_modal_save',
    },
    GEO_LOCATIONS_MODAL_DONT_SAVE_CLICKED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'geo_locations_modal_dont_save',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_access_point: 'modal',
      ui_object_detail: 'geo_locations_modal_dont_save',
    },
    // Mileage tracking toggle in time entry settings (geo-locations section)
    MILEAGE_TRACKING_TOGGLE: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'qbtime',
      scope_area: 'time-tracking',
      screen: 'geolocation_settings',
      object: 'widget',
      object_detail: 'mileage_toggle',
      action: 'engaged',
      ui_object: 'switch',
      ui_object_detail: 'mileage_tracking',
      ui_action: '', // enabled | disabled
    },
    // Geofence checkbox in geolocation settings (turn on geofence)
    GEOFENCE_CHECKBOX: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'geolocation_settings',
      action: 'engaged',
      object: 'widget',
      object_detail: 'geofence',
      ui_action: '', // enabled | disabled
      ui_object: 'checkbox',
      ui_object_detail: 'turn_on_geofence',
    },
    // Go to Assignments link in geolocation settings geofence section
    GEOFENCE_GO_TO_ASSIGNMENTS: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'geolocation_settings',
      action: 'viewed',
      object: 'widget',
      object_detail: 'geofence',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_object_detail: 'go_to_assignments',
    },
    // Set up geofence notifications button in geolocation settings
    GEOFENCE_SET_UP_NOTIFICATIONS: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'geolocation_settings',
      action: 'engaged',
      object: 'widget',
      object_detail: 'geofence',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_object_detail: 'set_up_geofence_notifications',
    },
    CONFIRMATION_MODAL_SAVE: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'timeentrymanagement',
      screen: 'single_time_entry',
      action: 'engaged',
      object: 'component',
      object_detail: 'confirmation_modal_save',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_object_detail: 'confirmation_modal_save',
      ui_access_point: 'modal',
    },
    CUSTOM_FIELD_EDIT: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'custom_field_edit',
      ui_action: 'clicked',
      ui_object: 'button',
      ui_access_point: 'page',
      ui_object_detail: 'custom_field_edit',
    },
    // Dimensions section: expand the collapsible section header
    DIMENSIONS_EXPAND: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'qbtime',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'expand_dimensions',
      ui_action: 'clicked',
      ui_object: 'widget',
      ui_object_detail: 'expand_dimensions',
      ui_access_point: 'page',
    },
    // Dimensions section: collapse the collapsible section header
    DIMENSIONS_COLLAPSE: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'qbtime',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'collapse_dimensions',
      ui_action: 'clicked',
      ui_object: 'widget',
      ui_object_detail: 'collapse_dimensions',
      ui_access_point: 'page',
    },
    // Dimensions section: "Set defaults" link
    DIMENSIONS_SET_DEFAULTS: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'qbtime',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'set_default_dimensions',
      ui_action: 'clicked',
      ui_object: 'link',
      ui_object_detail: 'set_default_dimensions',
      ui_access_point: 'page',
    },
    // Dimensions section: "Manage dimensions across all companies" link
    DIMENSIONS_MANAGE: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'qbtime',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'manage_dimensions',
      ui_action: 'clicked',
      ui_object: 'link',
      ui_object_detail: 'manage_dimensions',
      ui_access_point: 'page',
    },
    // Dimensions section: "Show on timesheet" toggle per dimension.
    // ui_object_detail is set dynamically: timesheet_fields_Dimension_<n>
    // ui_action is set dynamically: enabled | disabled
    DIMENSION_SHOW_ON_TIMESHEET: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'qbtime',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_Dimension',
      ui_action: '', // enabled | disabled
      ui_object: 'toggle',
      ui_object_detail: 'timesheet_fields_Dimension', // suffixed with _<n>
      ui_access_point: 'page',
    },
    // Dimensions section: "Required" toggle per dimension.
    // ui_object_detail is set dynamically: timesheet_fields_dimensions_<n>_required
    // ui_action is set dynamically: enabled | disabled
    DIMENSION_REQUIRED: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'qbtime',
      scope_area: 'time-tracking',
      screen: 'account-settings-time',
      action: 'engaged',
      object: 'widget',
      object_detail: 'timesheet_fields_dimension_required',
      ui_action: '', // enabled | disabled
      ui_object: 'toggle',
      ui_object_detail: 'timesheet_fields_dimensions_required', // dynamic: timesheet_fields_dimensions_<n>_required
      ui_access_point: 'page',
    },
  };
