export const TIME_KIOSK_LOGGING = {
  SETTINGS_HANDLE_EDIT_CLICKED:
    'Plugin=time-tracking-ui Event=TIME_KIOSK_SETTINGS_HANDLE_EDIT_CLICKED',
  FEATURE_CLOSED: 'Plugin=time-tracking-ui Event=TIME_KIOSK_FEATURE_CLOSED',
  EDIT_INACTIVITY_TIMEOUT_BUTTON_CLICKED:
    'Plugin=time-tracking-ui Event=TIME_KIOSK_EDIT_INACTIVITY_TIMEOUT_BUTTON_CLICKED',
  EDIT_LOCATION_RECORDING_BUTTON_CLICKED:
    'Plugin=time-tracking-ui Event=TIME_KIOSK_EDIT_LOCATION_RECORDING_BUTTON_CLICKED',
  USE_THIS_COMPUTER_BUTTON_CLICKED:
    'Plugin=time-tracking-ui Event=TIME_KIOSK_USE_THIS_COMPUTER_BUTTON_CLICKED',
  ADD_DEVICE_BUTTON_CLICKED:
    'Plugin=time-tracking-ui Event=TIME_KIOSK_ADD_DEVICE_BUTTON_CLICKED',
} as const;
