import { TrackingPoint } from '../../../common/useClickTracking';
import {
  BASE_TIME_TRACKING_FIELDS,
  TRACKING_ACTIONS,
  UI_ACTIONS,
  UI_OBJECTS,
} from '../../../common/trackingConstants';

// Groups-specific tracking point interface that extends the base TrackingPoint
export interface GroupsTrackingPoint extends TrackingPoint {
  previous_screen?: string;
}

// Groups-specific tracking points type
export interface GroupsTrackingPoints {
  [key: string]: GroupsTrackingPoint;
}

// Groups List Page Tracking Points
export const GROUPS_LIST_TRACKING_POINTS: GroupsTrackingPoints = {
  GROUPS_ENTRY: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.NAVIGATED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.LINK,
    ui_object_detail: 'groups_tab',
    ui_access_point: 'groups_tab',
    previous_screen: 'left_nav',
  },
  GROUPS_LIST_VIEW: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.VIEWED,
    ui_action: UI_ACTIONS.VIEWED,
    ui_object: UI_OBJECTS.PAGE,
    ui_object_detail: 'groups_list',
    ui_access_point: 'groups_list',
    previous_screen: 'groups_tab',
  },
  SEARCH_GROUPS: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.TYPED,
    ui_object: UI_OBJECTS.FORM_FIELD,
    ui_object_detail: 'search_groups',
    ui_access_point: 'search_groups',
    previous_screen: 'groups_list_header',
  },
  PAGINATION: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'groups_pagination',
    ui_access_point: 'pagination_control',
    previous_screen: 'groups_list_footer',
  },
  MANAGE_FIELDS: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'manage_fields',
    ui_access_point: 'manage_time_tracking_fields',
    previous_screen: 'groups_list_header',
  },
  // Sub tab in Workers tab to view worker list
  // worker_type: all, employee, user, vendor
  WORKERS_LIST_CLICKED: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    object: 'component',
    object_detail: 'groups_tab',
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.DROPDOWN,
    ui_object_detail: 'worker_type_dropdown',
    ui_access_point: 'center',
    previous_screen: 'workers_tab',
  },
};

// Create Group Drawer Tracking Points
export const CREATE_GROUP_TRACKING_POINTS: GroupsTrackingPoints = {
  START_CREATE_GROUP: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'create_group',
    ui_access_point: 'create_group_cta',
    previous_screen: 'groups_list_header',
  },
  VIEW_CREATE_DRAWER: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.VIEWED,
    object: UI_OBJECTS.DRAWER,
    object_detail: UI_OBJECTS.DRAWER,
    ui_action: UI_ACTIONS.VIEWED,
    ui_object: UI_OBJECTS.DRAWER,
    ui_object_detail: 'create_group_drawer',
    ui_access_point: 'create_group_drawer',
    previous_screen: 'create_group_cta',
  },
  TYPE_GROUP_NAME: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.TYPED,
    ui_object: UI_OBJECTS.FORM_FIELD,
    ui_object_detail: 'group_name_field',
    ui_access_point: 'group_name',
    previous_screen: 'create_group_drawer',
  },
  CLICK_ASSIGN_WORKERS: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'assign_workers',
    ui_access_point: 'assign_workers_cta',
    previous_screen: 'create_group_drawer',
  },
  CLICK_ASSIGN_LEADS: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'assign_leads',
    ui_access_point: 'assign_leads_cta',
    previous_screen: 'create_group_drawer',
  },
  SAVE_GROUP: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'save_group',
    ui_access_point: 'save_create_group',
    previous_screen: 'create_group_drawer',
  },
  CANCEL_GROUP: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'cancel_group',
    ui_access_point: 'cancel_create_group',
    previous_screen: 'create_group_drawer',
  },
  // Click "X" on create group drawer
  CLOSE_CREATE_GROUP_DRAWER: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    object: 'component',
    object_detail: 'create_group_drawer',
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'close_button',
    ui_access_point: 'center',
    previous_screen: 'create_group_drawer',
  },
};

// Group Row Actions Tracking Points
export const GROUP_ACTIONS_TRACKING_POINTS: GroupsTrackingPoints = {
  OPEN_GROUP_MENU: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'group_action_menu',
    ui_access_point: 'group_row_dropdown',
    previous_screen: 'groups_list_row',
  },
  EDIT_GROUP: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.LIST_ITEM,
    ui_object_detail: 'edit_group',
    ui_access_point: 'edit_group_option',
    previous_screen: 'group_row_dropdown',
  },
  ASSIGN_WORKERS_MENU: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.LIST_ITEM,
    ui_object_detail: 'assign_workers_menu',
    ui_access_point: 'assign_workers_option',
    previous_screen: 'group_row_dropdown',
  },
  ASSIGN_LEAD_MENU: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.LIST_ITEM,
    ui_object_detail: 'assign_lead_menu',
    ui_access_point: 'assign_group_lead_option',
    previous_screen: 'group_row_dropdown',
  },
  DELETE_GROUP: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.LIST_ITEM,
    ui_object_detail: 'delete_group',
    ui_access_point: 'delete_group_option',
    previous_screen: 'group_row_dropdown',
  },
  // Click "View" for a Group in Workers Tab
  VIEW_GROUP_CTA: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    object: 'component',
    object_detail: 'groups_list',
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'view_button',
    ui_access_point: 'center',
    previous_screen: 'groups_list',
  },
};

// Group Details Page Tracking Points
export const GROUP_DETAILS_TRACKING_POINTS: GroupsTrackingPoints = {
  VIEW_GROUP_DETAILS: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.VIEWED,
    ui_action: UI_ACTIONS.VIEWED,
    ui_object: UI_OBJECTS.PAGE,
    ui_object_detail: 'group_details',
    ui_access_point: 'group_details_page',
    previous_screen: 'group_name_link',
  },
  SEARCH_WORKERS_DETAIL: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.TYPED,
    ui_object: UI_OBJECTS.FORM_FIELD,
    ui_object_detail: 'search_group_workers',
    ui_access_point: 'search_workers',
    previous_screen: 'group_details_header',
  },
  FILTER_WORKERS_DETAIL: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.DROPDOWN,
    ui_object_detail: 'filter_group_workers',
    ui_access_point: 'workers_filter',
    previous_screen: 'group_details_header',
  },
  // Select "Assign" Dropdown
  ASSIGN_DROPDOWN_CLICKED: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    object: 'component',
    object_detail: 'group_details_page',
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.DROPDOWN,
    ui_object_detail: 'assign_dropdown',
    ui_access_point: 'center',
    previous_screen: 'group_details_page',
  },
  // Select "Assign workers"
  ASSIGN_WORKERS_OPTION_CLICKED: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    object: 'component',
    object_detail: 'group_details_page',
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.LIST_ITEM,
    ui_object_detail: 'assign_workers',
    ui_access_point: 'assign_dropdown',
    previous_screen: 'assign_dropdown',
  },
  // Select "Assign leads"
  ASSIGN_LEADS_OPTION_CLICKED: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    object: 'component',
    object_detail: 'group_details_page',
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.LIST_ITEM,
    ui_object_detail: 'assign_leads',
    ui_access_point: 'assign_dropdown',
    previous_screen: 'assign_dropdown',
  },
};

// Group Modals Tracking Points
export const GROUP_MODALS_TRACKING_POINTS: GroupsTrackingPoints = {
  VIEW_LEAD_MODAL: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.VIEWED,
    object: UI_OBJECTS.MODAL,
    object_detail: UI_OBJECTS.MODAL,
    ui_action: UI_ACTIONS.VIEWED,
    ui_object: UI_OBJECTS.MODAL,
    ui_object_detail: 'assign_lead_modal',
    ui_access_point: 'assign_lead_modal',
    previous_screen: 'group_action_menu',
  },
  SEARCH_LEAD: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.TYPED,
    ui_object: UI_OBJECTS.FORM_FIELD,
    ui_object_detail: 'search_leads',
    ui_access_point: 'search_leads',
    previous_screen: 'assign_lead_modal',
  },
  SELECT_LEAD: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.CHECKBOX,
    ui_object_detail: 'select_lead',
    ui_access_point: 'worker_checkbox',
    previous_screen: 'assign_lead_modal',
  },
  SELECT_ALL_LEADS: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.CHECKBOX,
    ui_object_detail: 'select_all_leads',
    ui_access_point: 'select_all_checkbox',
    previous_screen: 'assign_lead_modal',
  },
  SAVE_LEAD: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'save_lead',
    ui_access_point: 'save_assign_lead',
    previous_screen: 'assign_lead_modal',
  },
  CLOSE_LEAD_MODAL: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'close_lead_modal',
    ui_access_point: 'close_icon',
    previous_screen: 'assign_lead_modal',
  },
  VIEW_WORKER_MODAL: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.VIEWED,
    object: UI_OBJECTS.MODAL,
    object_detail: UI_OBJECTS.MODAL,
    ui_action: UI_ACTIONS.VIEWED,
    ui_object: UI_OBJECTS.MODAL,
    ui_object_detail: 'assign_worker_modal',
    ui_access_point: 'assign_worker_modal',
    previous_screen: 'group_action_menu',
  },
  SEARCH_WORKER: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.TYPED,
    ui_object: UI_OBJECTS.FORM_FIELD,
    ui_object_detail: 'search_workers',
    ui_access_point: 'search_workers',
    previous_screen: 'assign_worker_modal',
  },
  SELECT_WORKER: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.CHECKBOX,
    ui_object_detail: 'select_worker',
    ui_access_point: 'worker_checkbox',
    previous_screen: 'assign_worker_modal',
  },
  SELECT_ALL_WORKERS: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.CHECKBOX,
    ui_object_detail: 'select_all_workers',
    ui_access_point: 'select_all_checkbox',
    previous_screen: 'assign_worker_modal',
  },
  SAVE_WORKER: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'save_worker',
    ui_access_point: 'save_assign_worker',
    previous_screen: 'assign_worker_modal',
  },
  CLOSE_WORKER_MODAL: {
    ...BASE_TIME_TRACKING_FIELDS,
    action: TRACKING_ACTIONS.ENGAGED,
    ui_action: UI_ACTIONS.CLICKED,
    ui_object: UI_OBJECTS.BUTTON,
    ui_object_detail: 'close_worker_modal',
    ui_access_point: 'close_icon',
    previous_screen: 'assign_worker_modal',
  },
};
