// Logging Constants
export const WORKERS_LOGGING_CONSTANTS = {
  // API Error Logs
  API_ERRORS: {
    APOLLO_CLIENT_NOT_INITIALIZED: 'APOLLO_CLIENT_NOT_INITIALIZED',
  },

  // Navigation Logs
  NAVIGATION: {
    FEATURE_MOUNTED: 'FEATURE_MOUNTED',
  },
} as const;

export const WORKERS_LOGGING = {
  FEATURE_MOUNTED: WORKERS_LOGGING_CONSTANTS.NAVIGATION.FEATURE_MOUNTED,
  APOLLO_CLIENT_NOT_INITIALIZED:
    WORKERS_LOGGING_CONSTANTS.API_ERRORS.APOLLO_CLIENT_NOT_INITIALIZED,
} as const;
