import {
  TrackingPoints,
  createTrackingPoints,
} from '../../common/useClickTracking';

/**
 * Single Time Entry Tracking Points
 * This file contains all tracking points related to single time entry forms.
 * Separated from the main useClickTracking.ts to improve modularity and reduce bundle size.
 */

// Constants for tracking point field names
export const TRACKING_FIELD_NAMES = {
  ON_MOUNT: 'ON_MOUNT',
  START_DATE: 'START_DATE',
  END_DATE: 'END_DATE',
  TEAM_MEMBER: 'TEAM_MEMBER',
  CUSTOMER: 'CUSTOMER',
  PROJECT: 'PROJECT',
  LOCATION: 'LOCATION',
  MILEAGE: 'MILEAGE',
  AUTO_CALCULATE_MILEAGE: 'AUTO_CALCULATE_MILEAGE',
  SERVICE: 'SERVICE',
  CLASS: 'CLASS',
  PAY_TYPE: 'PAY_TYPE',
  BILLABLE: 'BILLABLE',
  TAXABLE: 'TAXABLE',
  NOTES: 'NOTES',
  BILL_RATE: 'BILL_RATE',
  COST_RATE: 'COST_RATE',
  CLOCK_IN: 'CLOCK_IN',
  CLOCK_OUT: 'CLOCK_OUT',
  DURATION: 'DURATION',
  START_TIME: 'START_TIME',
  END_TIME: 'END_TIME',
  TOGGLE_BREAK: 'TOGGLE_BREAK',
  BREAK_DURATION: 'BREAK_DURATION',
  CURRENTLY_WORKING: 'CURRENTLY_WORKING',
  TIMEZONE: 'TIMEZONE',
  CUSTOM_FIELD_LIST: 'CUSTOM_FIELD_LIST',
  CUSTOM_FIELD_TEXT: 'CUSTOM_FIELD_TEXT',
  CUSTOM_FIELD_DROPDOWN: 'CUSTOM_FIELD_DROPDOWN',
  CUSTOM_FIELD_NUMBER: 'CUSTOM_FIELD_NUMBER',
} as const;

// Base template for single time tracking points (both for time entry and time activity)
export const BASE_SINGLE_TIME_TRACKING_TEMPLATE = {
  ON_MOUNT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'navigated',
    object: 'component',
    object_detail: 'view_single_time_entry',
    ui_action: 'viewed',
    ui_object: 'page',
    ui_object_detail: 'view_single_time_entry',
  },
  START_DATE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_start_date_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_start_date_field',
    ui_access_point: 'modal',
  },
  END_DATE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_end_date_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_end_date_field',
    ui_access_point: 'modal',
  },
  TEAM_MEMBER: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_team_member_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_team_member_field',
    ui_access_point: 'modal',
  },
  CUSTOMER: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_customer_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_customer_field',
    ui_access_point: 'modal',
  },
  PROJECT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_project_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_project_field',
    ui_access_point: 'modal',
  },
  LOCATION: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_location_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_location_field',
    ui_access_point: 'modal',
  },
  // Mileage input field tracking (when user types mileage value)
  MILEAGE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'single_time_entry',
    action: 'engaged',
    object: 'widget',
    object_detail: 'time_add',
    ui_action: 'typed',
    ui_object: 'form_field',
    ui_object_detail: 'mileage',
  },
  // Auto-calculate mileage checkbox tracking
  AUTO_CALCULATE_MILEAGE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'single_time_entry',
    action: 'engaged',
    object: 'widget',
    object_detail: 'time_add',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'auto_calculate',
  },
  SERVICE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_service_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_service_field',
    ui_access_point: 'modal',
  },
  CLASS: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_class_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_class_field',
    ui_access_point: 'modal',
  },
  PAY_TYPE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_pay_type_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_pay_type_field',
    ui_access_point: 'modal',
  },
  BILLABLE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_billable_field',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'time_billable_field',
    ui_access_point: 'modal',
  },
  TAXABLE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_taxable_field',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'time_taxable_field',
    ui_access_point: 'modal',
  },
  NOTES: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_notes_field',
    ui_action: 'typed',
    ui_object: 'form_field',
    ui_object_detail: 'time_notes_field',
    ui_access_point: 'modal',
  },
  BILL_RATE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_bill_rate_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_bill_rate_field',
    ui_access_point: 'modal',
  },
  COST_RATE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_cost_rate_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_cost_rate_field',
    ui_access_point: 'modal',
  },
  CLOCK_IN: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'enabled',
    object: 'component',
    object_detail: 'clock_in_toggle',
    ui_action: 'enabled',
    ui_object: 'switch',
    ui_object_detail: 'clock_in_toggle',
    ui_access_point: 'modal',
  },
  CLOCK_OUT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'enabled',
    object: 'component',
    object_detail: 'clock_out_toggle',
    ui_action: 'enabled',
    ui_object: 'switch',
    ui_object_detail: 'clock_out_toggle',
    ui_access_point: 'modal',
  },
  DURATION: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'started',
    object: 'component',
    object_detail: 'duration_field',
    ui_action: 'typed',
    ui_object: 'form_field',
    ui_object_detail: 'duration_field',
    ui_access_point: 'modal',
  },
  START_TIME: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'started',
    object: 'component',
    object_detail: 'start_time',
    ui_action: 'clicked',
    ui_object: 'form_field',
    ui_object_detail: 'start_time',
    ui_access_point: 'modal',
  },
  END_TIME: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'started',
    object: 'component',
    object_detail: 'end_time',
    ui_action: 'clicked',
    ui_object: 'form_field',
    ui_object_detail: 'end_time',
    ui_access_point: 'modal',
  },
  TOGGLE_BREAK: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'started',
    object: 'component',
    object_detail: 'add_break',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'add_break',
    ui_access_point: 'modal',
  },
  BREAK_DURATION: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'started',
    object: 'component',
    object_detail: 'break_field',
    ui_action: 'typed',
    ui_object: 'form_field',
    ui_object_detail: 'break_field',
    ui_access_point: 'modal',
  },
  SETTINGS_GEAR: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'field_settings',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'field_settings',
    ui_access_point: 'modal',
  },
  SERVICE_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'service_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'service_field_settings',
    ui_access_point: 'panel',
  },
  BILLABLE_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'billable_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'billable_field_settings',
    ui_access_point: 'panel',
  },
  CLASS_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'class_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'class_field_settings',
    ui_access_point: 'panel',
  },
  PROJECT_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'qbo',
    action: 'edited',
    object: 'time',
    object_detail: 'project_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_access_point: 'panel',
  },
  LOCATION_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'location_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'location_field_settings',
    ui_access_point: 'panel',
  },
  PAY_TYPE_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'pay_type_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'pay_type_field_settings',
    ui_access_point: 'panel',
  },
  COST_RATE_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'cost_rate_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'cost_rate_field_settings',
    ui_access_point: 'panel',
  },
  TAXABLE_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'taxable_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'taxable_field_settings',
    ui_access_point: 'panel',
  },
  SAVE_SETTINGS: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'save_field_settings',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'save_field_settings',
    ui_access_point: 'panel',
  },
  CANCEL: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'cancel_time_sheet',
    ui_action: 'clicked',
    ui_object: 'link',
    ui_object_detail: 'cancel_time_sheet',
    ui_access_point: 'modal',
  },
  DELETE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'delete_time_sheet',
    ui_action: 'clicked',
    ui_object: 'link',
    ui_object_detail: 'delete_time_sheet',
    ui_access_point: 'modal',
  },
  SAVE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'save_time_sheet',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'save_time_sheet',
    ui_access_point: 'modal',
  },
  SAVE_AND_NEW: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'save_new_time_sheet',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'save_new_time_sheet',
    ui_access_point: 'modal',
  },
  SAVE_AND_CLOSE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'save_and_close_time_sheet',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'save_and_close_time_sheet',
    ui_access_point: 'modal',
  },
  // TODO: Make changes in instrumentation for save and copy if needed
  SAVE_AND_COPY: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'save_and_copy_time_sheet',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'save_and_copy_time_sheet',
    ui_access_point: 'modal',
  },
  FEEDBACK: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'feedback_time_sheet',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'feedback_time_sheet',
    ui_access_point: 'modal',
  },
  CLOSED_BOOK_PASSWORD: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'feedback_time_sheet',
    ui_action: 'typed',
    ui_object: 'textbox',
    ui_object_detail: 'feedback_time_sheet',
    ui_access_point: 'modal',
  },
  SEE_WHATS_NEW: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'see_whats_new',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'see_whats_new',
  },
  USE_PREVIOUS_EXPERIENCE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'use_previous_experience',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'use_previous_experience',
  },
  SEE_RECENT_TIME_ACTIVITIES: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_sheet_history',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'time_sheet_history',
  },
} as const;

// Tracking points for single time activity
// The screen name here is single_time_entry but it is used for tracking time activity
// The screen name was not changed to avoid breaking changes in already existing amplitude dashboards
export const SINGLE_TIME_TRACKING_POINTS: TrackingPoints = createTrackingPoints(
  'single_time_entry',
  BASE_SINGLE_TIME_TRACKING_TEMPLATE,
  {
    CURRENTLY_WORKING: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'timeentrymanagement',
      object: 'component',
      object_detail: 'currently_working',
      screen: 'single_time_entry',
      ui_action: '', // enabled | disabled
      ui_object: 'checkbox',
      ui_object_detail: 'currently_working',
      ui_access_point: '',
      action: 'engaged',
    },
    DIMENSION_DROPDOWN: {
      org: 'sbseg',
      purpose: 'prod',
      scope: 'time',
      scope_area: 'timeentrymanagement',
      screen: 'single_time_entry',
      action: 'engaged',
      object: 'component',
      object_detail: 'dimension_field_dropdown',
      ui_action: 'clicked',
      ui_object: 'dropdown',
      ui_object_detail: 'time_dimension_field',
      ui_access_point: 'modal',
    },
  },
);

// Tracking points for single time entry
export const SINGLE_TIME_ENTRY_TRACKING_POINTS: TrackingPoints =
  createTrackingPoints(
    'single_time_tracking_time_entry',
    BASE_SINGLE_TIME_TRACKING_TEMPLATE,
    {
      ON_MOUNT: {
        object_detail: 'view_single_time_tracking_time_entry',
        ui_object_detail: 'view_single_time_tracking_time_entry',
      },
      CURRENTLY_WORKING: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        screen: 'single_time_tracking_time_entry',
        object: 'component',
        object_detail: 'currently_working',
        ui_action: '', // enabled | disabled
        ui_object: 'checkbox',
        ui_object_detail: 'currently_working',
        ui_access_point: '',
        action: 'engaged',
      },
      TIMEZONE: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        screen: 'single_time_tracking_time_entry',
        object: 'component',
        object_detail: 'timezone',
        ui_action: 'clicked',
        ui_object: 'form_field',
        ui_object_detail: 'timezone',
        ui_access_point: 'modal',
        action: 'engaged',
      },
      CUSTOM_FIELD_LIST: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        screen: 'single_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'custom_field_list',
        ui_action: 'clicked',
        ui_object: 'list_item',
        ui_object_detail: 'custom_field_list',
        ui_access_point: 'modal',
      },
      CUSTOM_FIELD_TEXT: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        screen: 'single_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'custom_field_text',
        ui_action: 'typed',
        ui_object: 'form_field',
        ui_object_detail: 'custom_field_text',
        ui_access_point: 'modal',
      },
      CUSTOM_FIELD_DROPDOWN: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        screen: 'single_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'custom_field_dropdown',
        ui_action: 'clicked',
        ui_object: 'dropdown',
        ui_object_detail: 'custom_field_dropdown',
        ui_access_point: 'modal',
      },
      CUSTOM_FIELD_NUMBER: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        screen: 'single_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'custom_field_number',
        ui_action: 'typed',
        ui_object: 'textbox',
        ui_object_detail: 'custom_field_number',
        ui_access_point: 'modal',
      },
      DIMENSION_DROPDOWN: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        screen: 'single_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'dimension_field_dropdown',
        ui_action: 'clicked',
        ui_object: 'dropdown',
        ui_object_detail: 'time_dimension_field',
        ui_access_point: 'modal',
      },
    },
  );

// WFS (Workforce Solutions) tracking points matching PDF spec exactly
// Uses scope_area: 'workforce' via globalOverrides and includes all fields from the PDF specification
export const WFS_SINGLE_TIME_ENTRY_TRACKING_POINTS: TrackingPoints =
  createTrackingPoints(
    'single_time_entry',
    BASE_SINGLE_TIME_TRACKING_TEMPLATE,
    {
      ON_MOUNT: {
        object_detail: 'view_single_time_entry',
        ui_object_detail: 'view_single_time_entry',
      },
      // WFS-specific overrides for CLOCK_IN/CLOCK_OUT (map to same toggle per PDF spec)
      CLOCK_IN: {
        object_detail: 'set_start_and_end_start_toggle',
        ui_object_detail: 'set_start_and_end_start_toggle',
      },
      CLOCK_OUT: {
        object_detail: 'set_start_and_end_start_toggle',
        ui_action: 'disabled',
        ui_object_detail: 'set_start_and_end_start_toggle',
      },
      // Currently working checkbox (not in base template) - PDF spec: scope_area='workforce', screen='single_time_entry'
      CURRENTLY_WORKING: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'single_time_entry',
        object: 'component',
        object_detail: 'currently_working_field',
        ui_action: '', // enabled | disabled (set dynamically)
        ui_object: 'checkbox',
        ui_object_detail: 'currently_working_field',
        ui_access_point: 'modal',
        action: 'engaged',
      },
      // Timezone field (not in base template) - PDF spec: scope_area='workforce', screen='single_time_entry'
      TIMEZONE: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'single_time_entry',
        object: 'component',
        object_detail: 'timezone',
        ui_action: 'clicked',
        ui_object: 'form_field',
        ui_object_detail: 'timezone',
        ui_access_point: 'modal',
        action: 'started',
      },
      // WFS-specific field for timesheet history - PDF spec: scope_area='workforce', screen='single_time_entry'
      TIMESHEET_HISTORY: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'single_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'time_sheet_history',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'time_sheet_history',
        ui_access_point: 'drawer',
      },
      // Custom field tracking points for time entries - NOT in PDF spec, using workforce scope
      CUSTOM_FIELD_LIST: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'single_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'custom_field_list',
        ui_action: 'clicked',
        ui_object: 'list_item',
        ui_object_detail: 'custom_field_list',
        ui_access_point: 'modal',
      },
      CUSTOM_FIELD_TEXT: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'single_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'custom_field_text',
        ui_action: 'typed',
        ui_object: 'form_field',
        ui_object_detail: 'custom_field_text',
        ui_access_point: 'modal',
      },
      CUSTOM_FIELD_DROPDOWN: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'single_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'custom_field_dropdown',
        ui_action: 'clicked',
        ui_object: 'dropdown',
        ui_object_detail: 'custom_field_dropdown',
        ui_access_point: 'modal',
      },
      CUSTOM_FIELD_NUMBER: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'single_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'custom_field_number',
        ui_action: 'typed',
        ui_object: 'textbox',
        ui_object_detail: 'custom_field_number',
        ui_access_point: 'modal',
      },
      DIMENSION_DROPDOWN: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'single_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'time_dimension_field',
        ui_action: 'clicked',
        ui_object: 'dropdown',
        ui_object_detail: 'time_dimension_field',
        ui_access_point: 'modal',
      },
    },
    { scope_area: 'workforce' }, // Global override applied to ALL fields
  );

/**
 * Get the appropriate tracking points based on page type and environment
 * @param options - Configuration options
 * @param options.isSingleTimeEntry - Whether this is a single time entry page (vs time activity)
 * @param options.isWorkforce - Whether running in Workforce environment
 * @returns The appropriate TrackingPoints object
 */
export const getSingleTimeTrackingPoints = ({
  isSingleTimeEntry,
  isWorkforce,
}: {
  isSingleTimeEntry: boolean;
  isWorkforce: boolean;
}): TrackingPoints => {
  if (isSingleTimeEntry && isWorkforce) {
    return WFS_SINGLE_TIME_ENTRY_TRACKING_POINTS;
  }

  if (isSingleTimeEntry) {
    return SINGLE_TIME_ENTRY_TRACKING_POINTS;
  }

  return SINGLE_TIME_TRACKING_POINTS;
};
