import { TrackingEvent } from '@appfabric/sandbox-spec';

export interface TrackingPoint extends TrackingEvent {
  org: string;
  purpose: string;
  scope: string;
  scope_area: string;
  screen?: string;
  action: string;
  object: string;
  object_detail?: string;
  ui_action?: string;
  ui_object?: string;
  ui_object_detail?: string;
  ui_access_point?: string;
}

export interface TrackingPoints {
  [key: string]: TrackingPoint;
}

// Helper function to create tracking points with specific screen and overrides
export const createTrackingPoints = (
  screen: string,
  base: Record<string, TrackingPoint>,
  overrides: Record<string, Partial<TrackingPoint>> = {},
  globalOverrides?: Partial<TrackingPoint>,
): TrackingPoints => {
  const result: TrackingPoints = {};

  Object.entries(base).forEach(([key, basePoint]) => {
    const override = overrides[key];
    result[key] = {
      ...basePoint,
      screen,
      ...globalOverrides, // Apply global overrides to all base fields
      ...override, // Specific overrides take precedence
    };
  });

  // Add any additional properties that are not in the base template
  Object.entries(overrides).forEach(([key, override]) => {
    if (!(key in base)) {
      result[key] = {
        ...globalOverrides, // Apply global overrides to additional fields too
        ...override,
        screen,
        ...globalOverrides, // Apply global overrides to additional fields too
      } as TrackingPoint;
    }
  });

  return result;
};

// Base template for weekly time tracking points
export const BASE_WEEKLY_TIME_TRACKING_TEMPLATE = {
  ON_MOUNT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'navigated',
    object: 'component',
    object_detail: 'weekly_time_entry',
    ui_action: 'viewed',
    ui_object: 'page',
    ui_object_detail: 'weekly_time_entry',
  },
  TEAM_MEMBER: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_team_member_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_team_member_field',
    ui_access_point: 'modal',
  },
  WEEK: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_start_date_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_start_date_field',
    ui_access_point: 'modal',
  },
  CUSTOMER: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_customer_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_customer_field',
    ui_access_point: 'modal',
  },
  PROJECT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_project_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_project_field',
    ui_access_point: 'modal',
  },
  LOCATION: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_location_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_location_field',
    ui_access_point: 'modal',
  },
  SERVICE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_service_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_service_field',
    ui_access_point: 'modal',
  },
  CLASS: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'weekly_time_entry',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_class_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_class_field',
    ui_access_point: 'modal',
  },
  PAY_TYPE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_pay_type_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_pay_type_field',
    ui_access_point: 'modal',
  },
  BILLABLE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_billable_field',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'time_billable_field',
    ui_access_point: 'modal',
  },
  TAXABLE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'weekly_time_entry',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_taxable_field',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'time_taxable_field',
    ui_access_point: 'modal',
  },
  NOTES: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_notes_field',
    ui_action: 'typed',
    ui_object: 'form_field',
    ui_object_detail: 'time_notes_field',
    ui_access_point: 'modal',
  },
  BILL_RATE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_bill_rate_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_bill_rate_field',
    ui_access_point: 'modal',
  },
  COST_RATE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_cost_rate_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_cost_rate_field',
    ui_access_point: 'modal',
  },
  DURATION: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'weekly_time_entry',
    action: 'engaged',
    object: 'component',
    object_detail: 'duration_field',
    ui_action: 'clicked',
    ui_object: 'float_box',
    ui_object_detail: 'duration_field',
    ui_access_point: 'modal',
  },
  DELETE_ROW: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'deleted',
    object: 'component',
    object_detail: 'delete_time_entry',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'delete_time_entry',
  },
  SETTINGS_GEAR: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'field_settings',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'field_settings',
    ui_access_point: 'modal',
  },
  SERVICE_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'service_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'service_field_settings',
    ui_access_point: 'panel',
  },
  BILLABLE_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'weekly_time_entry',
    action: 'engaged',
    object: 'component',
    object_detail: 'billable_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'billable_field_settings',
    ui_access_point: 'panel',
  },
  CLASS_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'class_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'class_field_settings',
    ui_access_point: 'panel',
  },
  PROJECT_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'qbo',
    action: 'edited',
    object: 'time',
    object_detail: 'project_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_access_point: 'panel',
  },
  LOCATION_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'location_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'location_field_settings',
    ui_access_point: 'panel',
  },
  PAY_TYPE_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'pay_type_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'pay_type_field_settings',
    ui_access_point: 'panel',
  },
  COST_RATE_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'cost_rate_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'cost_rate_field_settings',
    ui_access_point: 'panel',
  },
  TAXABLE_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'taxable_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'taxable_field_settings',
    ui_access_point: 'panel',
  },
  MONDAY_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'monday_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'monday_field_settings',
    ui_access_point: 'panel',
  },
  TUESDAY_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'tuesday_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'tuesday_field_settings',
    ui_access_point: 'panel',
  },
  WEDNESDAY_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'weekly_time_entry',
    action: 'engaged',
    object: 'component',
    object_detail: 'wednesday_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'wednesday_field_settings',
    ui_access_point: 'panel',
  },
  THURSDAY_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'weekly_time_entry',
    action: 'engaged',
    object: 'component',
    object_detail: 'thursday_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'thursday_field_settings',
    ui_access_point: 'panel',
  },
  FRIDAY_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'friday_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'friday_field_settings',
    ui_access_point: 'panel',
  },
  SATURDAY_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'weekly_time_entry',
    action: 'engaged',
    object: 'component',
    object_detail: 'saturday_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'saturday_field_settings',
    ui_access_point: 'panel',
  },
  SUNDAY_SETTING: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'weekly_time_entry',
    action: 'engaged',
    object: 'component',
    object_detail: 'sunday_field_settings',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'sunday_field_settings',
    ui_access_point: 'panel',
  },
  SAVE_SETTINGS: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'weekly_time_entry',
    action: 'engaged',
    object: 'component',
    object_detail: 'save_field_settings',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'save_field_settings',
    ui_access_point: 'panel',
  },
  CANCEL: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'weekly_time_entry',
    action: 'engaged',
    object: 'component',
    object_detail: 'cancel_time_sheet',
    ui_action: 'clicked',
    ui_object: 'link',
    ui_object_detail: 'cancel_time_sheet',
    ui_access_point: 'modal',
  },
  SAVE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'save_time_sheet',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'save_time_sheet',
    ui_access_point: 'modal',
  },
  SAVE_AND_NEW: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'save_new_time_sheet',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'save_new_time_sheet',
    ui_access_point: 'modal',
  },
  SAVE_AND_CLOSE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'save_and_close_time_sheet',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'save_and_close_time_sheet',
    ui_access_point: 'modal',
  },
  FEEDBACK: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'feedback_time_sheet',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'feedback_time_sheet',
    ui_access_point: 'modal',
  },
  ADD_LINE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'add_time_entry_line',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'add_time_entry_line',
    ui_access_point: 'modal',
  },
  CLEAR_LINES: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'clear_time_entry_line',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'clear_time_entry_line',
    ui_access_point: 'modal',
  },
  PRINT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'print_time_sheet',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'print_time_sheet',
    ui_access_point: 'modal',
  },
  EXPORT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    screen: 'weekly_time_entry',
    action: 'engaged',
    object: 'component',
    object_detail: 'export_time_sheet',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'export_time_sheet',
    ui_access_point: 'modal',
  },
  COPY_LAST_SHEET: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'copy_time_sheet',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'copy_time_sheet',
    ui_access_point: 'modal',
  },
  CLOSED_BOOK_PASSWORD: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'feedback_time_sheet',
    ui_action: 'typed',
    ui_object: 'textbox',
    ui_object_detail: 'feedback_time_sheet',
    ui_access_point: 'modal',
  },
  SEE_WHATS_NEW: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'see_whats_new',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'see_whats_new',
  },
  USE_PREVIOUS_EXPERIENCE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'timeentrymanagement',
    action: 'engaged',
    object: 'component',
    object_detail: 'use_previous_experience',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'use_previous_experience',
  },
} as const;
// Create weekly time tracking points using the helper function

export const WEEKLY_TIME_TRACKING_POINTS: TrackingPoints = createTrackingPoints(
  'weekly_time_entry',
  BASE_WEEKLY_TIME_TRACKING_TEMPLATE,
  {
    // Additional weekly-specific tracking points can be added here
  },
);
// Tracking points for weekly time tracking time entry
export const WEEKLY_TIME_TRACKING_TIME_ENTRY: TrackingPoints =
  createTrackingPoints(
    'weekly_time_tracking_time_entry',
    BASE_WEEKLY_TIME_TRACKING_TEMPLATE,
    {
      // Additional weekly-specific tracking points can be added here
      CLEAR_ROW: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        action: 'clear row',
        object: 'component',
        object_detail: 'clear_row',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'clear_row',
        ui_access_point: 'menu within weekly cell',
      },
      COPY: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        action: 'copy',
        object: 'component',
        object_detail: 'copy',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'copy',
        ui_access_point: 'menu within weekly cell',
      },
      PASTE: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        action: 'paste',
        object: 'component',
        object_detail: 'paste',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'paste',
        ui_access_point: 'menu within weekly cell',
      },
      // Subject to change
      INSERT_ROW_BELOW: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        action: 'insert row',
        object: 'component',
        object_detail: 'insert_row',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'insert_row',
        ui_access_point: 'menu within weekly cell',
      },
      CLEAR_CELL: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        action: 'clear cell',
        object: 'component',
        object_detail: 'clear_cell',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'clear_cell',
        ui_access_point: 'menu within weekly cell',
      },
      WEEKDAY_CHANGE: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        action: 'engaged',
        object: 'component',
        object_detail: 'time_selected_day_field',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'time_selected_day_field',
        ui_access_point: 'panel',
      },
      LOCK_ICON_CLICK: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        action: 'engaged',
        object: 'component',
        object_detail: 'lock_icon_button',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'lock_icon_button',
        ui_access_point: 'modal',
      },
      RESET_FORM_STATE: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        action: 'reset',
        object: 'component',
        object_detail: 'reset_form',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'reset_form',
        ui_access_point: 'modal',
      },
      CUSTOM_FIELD_TEXT: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        screen: 'single_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'time_custom_field',
        ui_action: 'typed',
        ui_object: 'text',
        ui_object_detail: 'time_custom_field',
        ui_access_point: 'modal',
      },
      CUSTOM_FIELD_DROPDOWN: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        screen: 'single_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'time_custom_field',
        ui_action: 'clicked',
        ui_object: 'dropdown',
        ui_object_detail: 'time_custom_field',
        ui_access_point: 'modal',
      },
      CUSTOM_FIELD_NUMBER: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        screen: 'single_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'time_custom_field',
        ui_action: 'typed',
        ui_object: 'number',
        ui_object_detail: 'time_custom_field',
        ui_access_point: 'modal',
      },
      DIMENSION_DROPDOWN: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'timeentrymanagement',
        action: 'engaged',
        object: 'component',
        object_detail: 'time_dimension_field',
        ui_action: 'clicked',
        ui_object: 'dropdown',
        ui_object_detail: 'time_dimension_field',
        ui_access_point: 'modal',
      },
    },
  );

// WFS (Workforce Solutions) tracking points for weekly time entry
// Uses scope_area: 'workforce' via globalOverrides and screen: 'weekly_time_tracking_time_entry'
export const WFS_WEEKLY_TIME_TRACKING_TIME_ENTRY: TrackingPoints =
  createTrackingPoints(
    'weekly_time_tracking_time_entry',
    BASE_WEEKLY_TIME_TRACKING_TEMPLATE,
    {
      // Add missing fields from PDF spec
      DELETE: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'weekly_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'delete_time_sheet',
        ui_action: 'clicked',
        ui_object: 'link',
        ui_object_detail: 'delete_time_sheet',
        ui_access_point: 'modal',
      },
      CLEAR_ROW: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'weekly_time_tracking_time_entry',
        action: 'clear row',
        object: 'component',
        object_detail: 'clear_row',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'clear_row',
        ui_access_point: 'menu within weekly cell',
      },
      COPY: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'weekly_time_tracking_time_entry',
        action: 'copy',
        object: 'component',
        object_detail: 'copy',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'copy',
        ui_access_point: 'menu within weekly cell',
      },
      PASTE: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'weekly_time_tracking_time_entry',
        action: 'paste',
        object: 'component',
        object_detail: 'paste',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'paste',
        ui_access_point: 'menu within weekly cell',
      },
      // Custom fields - same pattern as WEEKLY_TIME_TRACKING_TIME_ENTRY
      CUSTOM_FIELD_TEXT: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'weekly_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'time_custom_field',
        ui_action: 'typed',
        ui_object: 'text',
        ui_object_detail: 'time_custom_field',
        ui_access_point: 'modal',
      },
      CUSTOM_FIELD_DROPDOWN: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'weekly_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'time_custom_field',
        ui_action: 'clicked',
        ui_object: 'dropdown',
        ui_object_detail: 'time_custom_field',
        ui_access_point: 'modal',
      },
      CUSTOM_FIELD_NUMBER: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'weekly_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'time_custom_field',
        ui_action: 'typed',
        ui_object: 'number',
        ui_object_detail: 'time_custom_field',
        ui_access_point: 'modal',
      },
      DIMENSION_DROPDOWN: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'weekly_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'time_dimension_field',
        ui_action: 'clicked',
        ui_object: 'dropdown',
        ui_object_detail: 'time_dimension_field',
        ui_access_point: 'modal',
      },
      INSERT_ROW_BELOW: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'weekly_time_tracking_time_entry',
        action: 'insert row',
        object: 'component',
        object_detail: 'insert_row',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'insert_row',
        ui_access_point: 'menu within weekly cell',
      },
      CLEAR_CELL: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'weekly_time_tracking_time_entry',
        action: 'clear cell',
        object: 'component',
        object_detail: 'clear_cell',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'clear_cell',
        ui_access_point: 'menu within weekly cell',
      },
      WEEKDAY_CHANGE: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'weekly_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'time_selected_day_field',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'time_selected_day_field',
        ui_access_point: 'panel',
      },
      LOCK_ICON_CLICK: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'weekly_time_tracking_time_entry',
        action: 'engaged',
        object: 'component',
        object_detail: 'lock_icon_button',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'lock_icon_button',
        ui_access_point: 'modal',
      },
      RESET_FORM_STATE: {
        org: 'sbseg',
        purpose: 'prod',
        scope: 'time',
        scope_area: 'workforce',
        screen: 'weekly_time_tracking_time_entry',
        action: 'reset',
        object: 'component',
        object_detail: 'reset_form',
        ui_action: 'clicked',
        ui_object: 'button',
        ui_object_detail: 'reset_form',
        ui_access_point: 'modal',
      },
    },
    { scope_area: 'workforce' }, // Global override applied to ALL fields
  );

/**
 * Get the appropriate weekly time tracking points based on environment
 * @param options - Configuration options
 * @param options.isWorkforce - Whether running in Workforce environment
 * @returns The appropriate TrackingPoints object
 */
export const getWeeklyTimeTrackingPoints = ({
  isWorkforce,
}: {
  isWorkforce: boolean;
}): TrackingPoints => {
  if (isWorkforce) {
    return WFS_WEEKLY_TIME_TRACKING_TIME_ENTRY;
  }
  return WEEKLY_TIME_TRACKING_TIME_ENTRY;
};

// Base template for time clock tracking points
const BASE_CLOCK_IN_TRACKING_TEMPLATE = {
  ON_MOUNT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'navigated',
    object: 'drawer',
    object_detail: 'view_time_clock',
    ui_action: 'viewed',
    ui_object: 'page',
    ui_object_detail: 'view_time_clock',
    ui_access_point: 'add_time_dropdown',
  },
  CLOCK_IN_ON_MOUNT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'drawer',
    object_detail: 'view_clock_in',
    ui_action: 'viewed',
    ui_object: 'drawer',
    ui_object_detail: 'clock_out_banner',
    ui_access_point: 'add_time_dropdown',
  },
  CLOCK_OUT_ON_MOUNT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'drawer',
    object_detail: 'view_clock_out',
    ui_action: 'viewed',
    ui_object: 'drawer',
    ui_object_detail: 'clocked_in_banner',
    ui_access_point: 'clock_in_button',
  },
  CLOCK_IN: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'clock_in_button',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'clock_in_button',
    ui_access_point: 'drawer',
  },
  START_DATE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_start_date_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_start_date_field',
    ui_access_point: 'drawer',
  },
  SWITCH_JOB: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock_out',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_switch_job_field',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'time_switch_job_field',
    ui_access_point: 'drawer',
  },
  SWITCH_JOB_DROPDOWN: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock_out',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_switch_job_dropdown',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_switch_job_dropdown',
    ui_access_point: 'drawer',
  },
  START_TIME: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_start_time_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_start_time_field',
    ui_access_point: 'drawer',
  },
  CUSTOMER: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_customer_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_customer_field',
    ui_access_point: 'drawer',
  },
  PROJECT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_project_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_project_field',
    ui_access_point: 'drawer',
  },
  NOTES: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_notes_field',
    ui_action: 'typed',
    ui_object: 'textbox',
    ui_object_detail: 'time_notes_field',
    ui_access_point: 'drawer',
  },
  TIMEZONE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_timezone_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_timezone_field',
  },
  CLOCK_OUT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_clock_out_button',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'time_clock_out_button',
    ui_access_point: 'drawer',
  },
  TIME_CLOCK_EXIT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_clock_exit',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'time_clock_exit',
    ui_access_point: 'drawer',
  },
  WANT_TO_SAVE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'viewed',
    object: 'component',
    object_detail: 'time_clock_save_page',
    ui_action: 'clicked',
    ui_object: 'page',
    ui_object_detail: 'time_clock_save_page',
    ui_access_point: 'drawer',
  },
  DONT_SAVE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_clock_dont_save',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'time_clock_dont_save',
    ui_access_point: 'drawer',
  },
  SAVE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_clock_save_button',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'time_clock_save_button',
    ui_access_point: 'drawer',
  },
  SERVICE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_service_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_service_field',
    ui_access_point: 'drawer',
  },
  CLASS: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_class_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_class_field',
    ui_access_point: 'drawer',
  },
  LOCATION: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_location_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_location_field',
    ui_access_point: 'drawer',
  },
  BILL_RATE_CHECKBOX: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_bill_rate_checkbox',
    ui_action: 'clicked',
    ui_object: 'checkbox',
    ui_object_detail: 'time_bill_rate_checkbox',
    ui_access_point: 'drawer',
  },
  BILL_RATE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_bill_rate_field',
    ui_action: 'typed',
    ui_object: 'textbox',
    ui_object_detail: 'time_bill_rate_field',
    ui_access_point: 'drawer',
  },
  CUSTOM_FIELD_LIST: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'custom_field_list',
    ui_action: 'clicked',
    ui_object: 'list_item',
    ui_object_detail: 'custom_field_list',
    ui_access_point: 'drawer',
  },
  CUSTOM_FIELD_TEXT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'custom_field_text',
    ui_action: 'typed',
    ui_object: 'form_field',
    ui_object_detail: 'custom_field_text',
    ui_access_point: 'drawer',
  },
  CUSTOM_FIELD_DROPDOWN: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'custom_field_dropdown',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'custom_field_dropdown',
    ui_access_point: 'drawer',
  },
  CUSTOM_FIELD_NUMBER: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'custom_field_number',
    ui_action: 'typed',
    ui_object: 'textbox',
    ui_object_detail: 'custom_field_number',
    ui_access_point: 'drawer',
  },
  DIMENSION_DROPDOWN: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'time_dimension_field',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'time_dimension_field',
    ui_access_point: 'drawer',
  },
  TAKE_BREAK: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'take_break_button',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'take_break_button',
    ui_access_point: 'drawer',
  },
  SELECT_BREAK_TYPE_DRAWER: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'select_break_type',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'break type',
    ui_access_point: 'drawer',
  },
  BREAK_BUTTON_CLICK: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'break_button',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'break_button',
    ui_access_point: 'drawer',
  },
  END_BREAK: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time_clock',
    scope_area: 'time_clock',
    screen: 'time_clock',
    action: 'engaged',
    object: 'component',
    object_detail: 'end_break_button',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'end_break_button',
    ui_access_point: 'drawer',
  },
} as const;

// QBO (QuickBooks Online) tracking points for time clock
export const CLOCK_IN_TRACKING_POINTS: TrackingPoints = createTrackingPoints(
  'time_clock',
  BASE_CLOCK_IN_TRACKING_TEMPLATE,
  {
    ON_MOUNT: {
      scope: 'time',
    },
  },
);

export const WFS_CLOCK_IN_TRACKING_POINTS: TrackingPoints =
  createTrackingPoints(
    'time_clock',
    BASE_CLOCK_IN_TRACKING_TEMPLATE,
    {
      ON_MOUNT: {
        object: 'component',
      },
      CLOCK_IN_ON_MOUNT: {
        action: 'navigated',
        ui_access_point: 'add_time_dropdown',
      },
      CLOCK_OUT_ON_MOUNT: {
        ui_access_point: 'clock_in_button',
      },
      CUSTOM_FIELD_LIST: {
        object: 'widget',
        object_detail: 'time_clock',
        ui_object_detail: 'custom field list',
        ui_access_point: 'admin',
      },
      CUSTOM_FIELD_TEXT: {
        ui_action: 'clicked',
        object: 'widget',
        object_detail: 'time_clock',
        ui_object_detail: 'custom field text',
        ui_access_point: 'admin',
      },
      CUSTOM_FIELD_DROPDOWN: {
        object: 'widget',
        object_detail: 'time_clock',
        ui_object_detail: 'custom field dropdown',
        ui_access_point: 'admin',
      },
      TAKE_BREAK: {
        object: 'widget',
        object_detail: 'time_clock',
        ui_object_detail: 'time_clock_takebreak',
      },
      SELECT_BREAK_TYPE_DRAWER: {
        object: 'widget',
        object_detail: 'time_clock',
      },
      BREAK_BUTTON_CLICK: {
        object: 'widget',
        object_detail: 'time_clock',
        ui_object: 'button',
        ui_object_detail: 'break_type_takebreak',
      },
      END_BREAK: {
        object: 'widget',
        object_detail: 'time_clock',
        ui_object_detail: 'time_clock_endbreak',
      },
      SAVE: {
        object: 'component',
        object_detail: 'time_clock_save_button',
        ui_object_detail: 'time_clock_save_button',
      },
      CLOCK_OUT: {
        ui_object_detail: 'time_clock_clock_out',
      },
      WANT_TO_SAVE: {
        action: 'viewed',
        ui_action: 'viewed',
      },
      DONT_SAVE: {
        object: 'widget',
      },
      TIME_CLOCK_EXIT: {},
    },
    { scope_area: 'workforce', scope: 'time_clock' },
  );

/**
 * Get the appropriate time clock tracking points based on environment
 * @param options - Configuration options
 * @param options.isWorkforce - Whether running in Workforce environment
 * @returns The appropriate TrackingPoints object
 */
export const getTimeClockTrackingPoints = ({
  isWorkforce,
}: {
  isWorkforce: boolean;
}): TrackingPoints => {
  if (isWorkforce) {
    return WFS_CLOCK_IN_TRACKING_POINTS;
  }
  return CLOCK_IN_TRACKING_POINTS;
};

export const TIME_ACTIVITY_SETTINGS_TRACKING_POINTS: TrackingPoints = {
  ON_MOUNT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'account-settings-time',
    action: 'navigated',
    object: 'drawer',
    object_detail: 'view_time_activity_settings',
    ui_action: 'viewed',
    ui_object: 'page',
    ui_object_detail: 'view_time_activity_settings',
    ui_access_point: 'page',
  },
  GENERAL_SECTION_SAVE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'account-settings-time',
    action: 'engaged',
    object: 'widget',
    object_detail: 'general_section_save',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'general_section_save',
    ui_access_point: 'page',
  },
  GENERAL_SECTION_EDIT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'account-settings-time',
    action: 'engaged',
    object: 'widget',
    object_detail: 'general_section_edit',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'general_section_edit',
    ui_access_point: 'page',
  },
  TIMESHEET_SECTION_SAVE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'account-settings-time',
    action: 'engaged',
    object: 'widget',
    object_detail: 'timesheet_section_save',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'timesheet_section_save',
    ui_access_point: 'page',
  },
  TIMESHEET_EDIT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'account-settings-time',
    action: 'engaged',
    object: 'widget',
    object_detail: 'timesheet_edit',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'timesheet_edit',
    ui_access_point: 'page',
  },
  GENERAL_SECTION_FIRST_DAY_OF_WEEK: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'account-settings-time',
    action: 'engaged',
    object: 'widget',
    object_detail: 'general_section_first_day_of_week',
    ui_action: 'clicked',
    ui_object: 'dropdown',
    ui_object_detail: 'general_section_first_day_of_week',
    ui_access_point: 'page',
  },
  TIMESHEET_SERVICE_ITEM: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'account-settings-time',
    action: 'engaged',
    object: 'widget',
    object_detail: 'timesheet_service_item',
    ui_action: '', // enabled | disabled
    ui_object: 'button',
    ui_object_detail: 'timesheet_service_item',
    ui_access_point: 'page',
  },
  TIMESHEET_BILLABLE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'account-settings-time',
    action: 'engaged',
    object: 'widget',
    object_detail: 'timesheet_billable',
    ui_action: '', // enabled | disabled
    ui_object: 'button',
    ui_object_detail: 'timesheet_billable',
    ui_access_point: 'page',
  },
  TIMESHEET_BILL_RATE_PER_HOUR: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'account-settings-time',
    action: 'engaged',
    object: 'widget',
    object_detail: 'timesheet_bill_rate_per_hour',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'timesheet_bill_rate_per_hour',
    ui_access_point: 'page',
  },
  TIMESHEET_SECTION_CANCEL: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'account-settings-time',
    action: 'engaged',
    object: 'widget',
    object_detail: 'timesheet_section_cancel',
    ui_action: 'cancel',
    ui_object: 'button',
    ui_object_detail: 'timesheet_section_cancel',
    ui_access_point: 'page',
  },
  GENERAL_SECTION_CANCEL: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'account-settings-time',
    action: 'engaged',
    object: 'widget',
    object_detail: 'general_section_cancel',
    ui_action: 'cancel',
    ui_object: 'button',
    ui_access_point: 'page',
    ui_object_detail: 'general_section_cancel',
  },
};

export const CUSTOM_FIELDS_TRACKING_POINTS: TrackingPoints = {
  CUSTOM_FIELDS_PAGE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_page',
    action: 'engaged',
    object: 'widget',
    object_detail: 'custom_fields_page',
    ui_action: 'viewed',
    ui_object: 'page',
    ui_object_detail: 'custom_fields_page',
    ui_access_point: 'page',
  },
  CUSTOM_FIELDS_ADD_BUTTON: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_page',
    action: 'engaged',
    object: 'widget',
    object_detail: 'add_custom_fields',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'add_custom_fields',
    ui_access_point: 'page',
  },
  CUSTOM_FIELDS_EDIT_LINK: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_page',
    action: 'engaged',
    object: 'widget',
    object_detail: 'edit_link',
    ui_action: 'clicked',
    ui_object: 'link',
    ui_object_detail: 'edit_link',
    ui_access_point: 'page',
  },
  CUSTOM_FIELDS_REQUIRED_SLIDER: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_page',
    action: 'engaged',
    object: 'widget',
    object_detail: 'required_slider',
    ui_action: 'clicked',
    ui_object: 'switch',
    ui_object_detail: 'required_slider',
    ui_access_point: 'page',
  },
  CUSTOM_FIELDS_DRAWER: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_drawer',
    action: 'engaged',
    object: 'widget',
    object_detail: 'custom_fields_drawer',
    ui_action: 'viewed',
    ui_object: 'drawer',
    ui_object_detail: 'custom_fields_drawer',
    ui_access_point: 'drawer',
  },
  CUSTOM_FIELDS_MANAGE_ASSIGNMENTS: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_drawer',
    action: 'engaged',
    object: 'widget',
    object_detail: 'manage_assignments',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'manage_assignments',
    ui_access_point: 'drawer',
  },
  CUSTOM_FIELDS_SAVE_BUTTON: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_drawer',
    action: 'engaged',
    object: 'widget',
    object_detail: 'save_button',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'save_button',
    ui_access_point: 'drawer',
  },
  CUSTOM_FIELDS_CONFIRM_CLOSE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_drawer',
    action: 'engaged',
    object: 'widget',
    object_detail: 'confirm_close',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'confirm_close',
    ui_access_point: 'drawer',
  },
  CUSTOM_FIELDS_CLOSE_WITH_UNSAVED_CHANGES: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_drawer',
    action: 'engaged',
    object: 'widget',
    object_detail: 'close_with_unsaved_changes',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'close_with_unsaved_changes',
    ui_access_point: 'drawer',
  },
  CUSTOM_FIELDS_CLOSE_WITHOUT_UNSAVED_CHANGES: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_drawer',
    action: 'engaged',
    object: 'widget',
    object_detail: 'close_without_unsaved_changes',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'close_without_unsaved_changes',
    ui_access_point: 'drawer',
  },
  CUSTOM_FIELD_TOUR_MODAL_OPEN: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_drawer',
    action: 'engaged',
    object: 'widget',
    object_detail: 'custom_field_tour_modal_open',
    ui_action: 'viewed',
    ui_object: 'modal',
    ui_object_detail: 'custom_field_tour_modal_open',
    ui_access_point: 'modal',
  },
  CUSTOM_FIELD_TOUR_MODAL_CLOSE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_drawer',
    action: 'engaged',
    object: 'widget',
    object_detail: 'custom_field_tour_modal_close',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'custom_field_tour_modal_close',
    ui_access_point: 'modal',
  },
  CUSTOM_FIELD_TOUR_MODAL_FINISH: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_drawer',
    action: 'engaged',
    object: 'widget',
    object_detail: 'custom_field_tour_modal_completed',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'custom_field_tour_modal_completed',
    ui_access_point: 'modal',
  },
  CUSTOM_FIELD_TOUR_MODAL_FAILED: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_drawer',
    action: 'engaged',
    object: 'widget',
    object_detail: 'custom_field_tour_modal_failed',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'custom_field_tour_modal_failed',
    ui_access_point: 'modal',
  },
  CUSTOM_FIELDS_CUSTOMER_ASSIGNMENT_CLICK: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_drawer',
    action: 'engaged',
    object: 'widget',
    object_detail: 'customer_assignment_click',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'customer_assignment_click',
    ui_access_point: 'drawer',
  },
  CUSTOM_FIELDS_WORKER_ASSIGNMENT_CLICK: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'custom-field',
    screen: 'custom_fields_drawer',
    action: 'engaged',
    object: 'widget',
    object_detail: 'worker_assignment_click',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'worker_assignment_click',
    ui_access_point: 'drawer',
  },
};

export const APPROVAL_SETTINGS_TRACKING_FIELDS: TrackingPoints = {
  // Approval Settings Section
  APPROVAL_SETTINGS_SECTION_EDIT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: 'approval_settings_section',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'edit',
    ui_access_point: 'page',
  },
  APPROVAL_SETTINGS_SECTION_SAVE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: 'approval_settings_section',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'save',
    ui_access_point: 'page',
  },
  APPROVAL_SETTINGS_SECTION_CANCEL: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: 'approval_settings_section',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'cancel',
    ui_access_point: 'page',
  },
  APPROVAL_REQUIRE_APPROVALS: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: 'approval_settings_section',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'require_approvals_on',
    ui_access_point: 'page',
  },
  APPROVAL_TEAM_MEMBER_SUBMIT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: 'approval_settings_section',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'team_member_submit_on',
    ui_access_point: 'page',
  },
  APPROVAL_REQUIRE_FULL_WEEK: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: 'approval_settings_section',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'require_full_week_on',
    ui_access_point: 'page',
  },
  APPROVAL_MANDATORY_TEAM_MEMBER_SUBMISSION: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: 'approval_settings_section',
    ui_action: '', // enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'mandatory_team_member_submission_on',
    ui_access_point: 'page',
  },
  APPROVAL_RESET_MESSAGE_BUTTON: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: 'approval_settings_section',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'reset_message_button',
    ui_access_point: 'page',
  },
  APPROVAL_CUSTOM_MESSAGE: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: 'approval_settings_section',
    ui_action: 'typed',
    ui_object: 'textbox',
    ui_object_detail: 'custom_message',
    ui_access_point: 'page',
  },
  // Generic Notifications tracking - dynamically set object_detail and ui_object_detail
  NOTIFICATION_RADIOBUTTON: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: '', // Set dynamically: notifications_approvals | notifications_submissions
    ui_action: 'selected',
    ui_object: 'radiobutton',
    ui_object_detail: '', // Set dynamically: day_of_week | pay_period | daily
    ui_access_point: 'page',
  },
  NOTIFICATION_REMINDER_CHECKBOX: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: '', // Set dynamically: notifications_approvals | notifications_submissions
    ui_action: '', // Set dynamically: enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: '', // Set dynamically based on mode and context
    ui_access_point: 'page',
  },
  NOTIFICATION_TIME_DROPDOWN: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: '', // Set dynamically: notifications_approvals | notifications_submissions
    ui_action: 'engaged',
    ui_object: 'dropdown',
    ui_object_detail: '', // Set dynamically based on mode and context
    ui_access_point: 'page',
  },
  NOTIFICATION_DAY_DROPDOWN: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: '', // Set dynamically: notifications_approvals | notifications_submissions
    ui_action: 'engaged',
    ui_object: 'dropdown',
    ui_object_detail: '', // Set dynamically based on mode and context
    ui_access_point: 'page',
  },
  NOTIFICATION_EMAIL_ON_SUBMIT: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: 'notifications_submissions',
    ui_action: '', // Set dynamically: enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'email_manager_on_submit',
    ui_access_point: 'page',
  },
  NOTIFICATION_EMAIL_ON_GROUP_SUBMITTED: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'time-settings',
    action: 'engaged',
    object: 'widget',
    object_detail: 'notifications_submissions',
    ui_action: '', // Set dynamically: enabled | disabled
    ui_object: 'checkbox',
    ui_object_detail: 'email_manager_on_group_submit', // Set dynamically: email_manager_on_submit_on | email_manager_on_group_submitted_on
    ui_access_point: 'page',
  },
};

export const SETTINGS_FLYOUT_V2_TRACKING_POINTS: TrackingPoints = {
  CONTENT_VIEWED: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'account-settings-time',
    action: 'navigated',
    object: 'widget',
    object_detail: 'settings_flyout_v2',
    ui_action: 'viewed',
    ui_object: 'card',
    ui_object_detail: 'settings_flyout_v2',
    ui_access_point: 'page',
  },
  UPGRADE_CLICKED: {
    org: 'sbseg',
    purpose: 'prod',
    scope: 'time',
    scope_area: 'time-tracking',
    screen: 'account-settings-time',
    action: 'engaged',
    object: 'widget',
    object_detail: 'settings_flyout_v2',
    ui_action: 'clicked',
    ui_object: 'button',
    ui_object_detail: 'upgrade_to_time',
    ui_access_point: 'page',
  },
};
