import React from 'react';
import styled from 'styled-components';
import { B2 } from '@ids-ts/typography';
import { AiSparkles } from '@design-systems/icons';
import { IconControl } from '@ids-ts/icon-control';

interface AIBannerProps {
  children: React.ReactNode;
  hasError?: boolean;
}

const AIBanner: React.FC<AIBannerProps> = ({ children, hasError = false }) => (
  <BannerContainer hasError={hasError}>
    <svg width="0" height="0" style={{ position: 'absolute' }}>
      <defs>
        <linearGradient
          id="ai-sparkles-gradient"
          x1="0%"
          y1="0%"
          x2="100%"
          y2="0%"
        >
          <stop
            offset="0%"
            style={{ stopColor: 'rgb(0, 208, 224)', stopOpacity: 1 }}
          />
          <stop
            offset="30%"
            style={{ stopColor: 'rgb(35, 108, 255)', stopOpacity: 1 }}
          />
          <stop
            offset="40%"
            style={{ stopColor: 'rgb(0, 208, 224)', stopOpacity: 1 }}
          />
          <stop
            offset="75%"
            style={{ stopColor: 'rgb(197, 239, 113)', stopOpacity: 1 }}
          />
          <stop
            offset="100%"
            style={{ stopColor: 'rgb(0, 166, 59)', stopOpacity: 1 }}
          />
        </linearGradient>
      </defs>
    </svg>
    <IconControl size="medium" aria-label="AI generated">
      <StyledAiSparkles size="xlarge" />
    </IconControl>
    <ContentWrapper>
      {children}
      <B2 as="div">
        Results are generated by AI, make sure to review before continuing.
      </B2>
    </ContentWrapper>
  </BannerContainer>
);

export default AIBanner;

// Styled Components
const BannerContainer = styled.div<{ hasError: boolean }>`
  display: flex;
  align-items: flex-start;
  gap: 12px;
  padding: 16px;
  background: linear-gradient(white, white) padding-box,
    linear-gradient(
        90deg,
        rgb(0, 208, 224) 0%,
        rgb(35, 108, 255) 25%,
        rgb(0, 208, 224) 50%,
        rgb(197, 239, 113) 75%,
        rgb(0, 166, 59) 100%
      )
      border-box;
  border: 2px solid transparent;
  border-radius: 8px;
  margin-bottom: 24px;
`;

const StyledAiSparkles = styled(AiSparkles)`
  fill: url(#ai-sparkles-gradient);

  /* Ensure all SVG paths use the gradient */
  path {
    fill: url(#ai-sparkles-gradient);
  }
`;

const ContentWrapper = styled.div`
  flex: 1;
`;

export const BannerText = styled(B2)`
  flex: 1;
`;
